#!/usr/bin/env python3
"""Generates tests/data/compress/*: zlib streams from Python's stdlib `zlib` (an independent
encoder; ARCHITECTURE §0's host-tool exception) for libs/compress's host tests (M12.2, D-140).
For each input <name>.raw it writes <name>.z1/.z6/.z9 (zlib levels 1/6/9: fixed and dynamic
Huffman blocks with real LZ77 matches) and, for the small inputs, <name>.z0 (stored blocks).

Run manually (`python3 tests/data/compress/gen.py`) when adding fixtures; the outputs are checked
in, not regenerated by the build.
"""
import os
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))


def xorshift(seed, n):
    out = bytearray()
    x = seed
    for _ in range(n):
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= x >> 17
        x ^= (x << 5) & 0xFFFFFFFF
        out.append(x & 0xFF)
    return bytes(out)


def text(n):
    words = ["kernel", "pixel", "surface", "the", "and", "compress", "window",
             "inflate", "canvas", "glyph", "alpha"]
    out = []
    x = 12345
    size = 0
    while size < n:
        x = (x * 1103515245 + 12345) & 0x7FFFFFFF
        w = words[(x >> 8) % len(words)] + (" " if (x >> 4) % 7 else ".\n")
        out.append(w)
        size += len(w)
    return "".join(out).encode()[:n]


INPUTS = {
    "empty": b"",
    "one": b"A",
    "zeros": bytes(20000),  # one dynamic block with a single distance code
    "text": text(12000),
    "noise": xorshift(0xC0FFEE, 9000),  # incompressible: stored or literal-only blocks
    "ramp": bytes((i * 7 + (i >> 5)) & 0xFF for i in range(30000)),  # long distances and matches
}

for name, data in INPUTS.items():
    with open(os.path.join(HERE, name + ".raw"), "wb") as f:
        f.write(data)
    # Stored blocks (level 0) only for the small text: for the rest they'd just repeat the input.
    for level in ((0, 1, 6, 9) if name in ("text", "one", "empty") else (1, 6, 9)):
        with open(os.path.join(HERE, "%s.z%d" % (name, level)), "wb") as f:
            f.write(zlib.compress(data, level))
