#!/usr/bin/env python3
"""Generates tests/data/gfx/decode-fixtures.z for libs/gfx's PNG/BMP decoder tests (M12.2, D-146).

An independent encoder (Python stdlib only; ARCHITECTURE §0's host-tool exception) writes many PNG
and BMP files across the spec's color types, bit depths, interlacing, filters, tRNS, DIB headers,
bit-field masks and orientations, and computes each file's expected premultiplied-ARGB pixels
directly from the format rules. libs/gfx's decoder must reproduce them exactly, so the decoder is
checked against something other than itself.

Container (zlib-compressed as a whole), a sequence of records:
  u16 nameLen, name, u8 kind (1 = PNG, 2 = BMP), u32 width, u32 height, u32 dataLen, data,
  then width*height little-endian u32 expected pixels (premultiplied 0xAARRGGBB).

Run manually (`python3 tests/data/gfx/gen.py`) when adding fixtures; the output is checked in, not
regenerated by the build.
"""
import os
import random
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))


def mul255(c, a):
    return (c * a + 127) // 255  # round to nearest (never a tie: 255 is odd)


def premul(r, g, b, a):
    return (a << 24) | (mul255(r, a) << 16) | (mul255(g, a) << 8) | mul255(b, a)


# ---------------------------------------------------------------- PNG ----------------------

CHANNELS = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}


def chunk(t, b):
    return struct.pack(">I", len(b)) + t + b + struct.pack(">I", zlib.crc32(t + b) & 0xFFFFFFFF)


def pack_samples(samples, depth):
    if depth >= 8:
        if depth == 8:
            return bytes(samples)
        out = bytearray()
        for s in samples:
            out += struct.pack(">H", s)
        return bytes(out)
    out = bytearray()
    cur, nbits = 0, 0
    for s in samples:
        cur = (cur << depth) | s
        nbits += depth
        if nbits == 8:
            out.append(cur)
            cur, nbits = 0, 0
    if nbits:
        out.append(cur << (8 - nbits))
    return bytes(out)


def paeth(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    return b if pb <= pc else c


def filter_row(ft, cur, prev, bpp):
    out = bytearray()
    for i, x in enumerate(cur):
        a = cur[i - bpp] if i >= bpp else 0
        b = prev[i]
        c = prev[i - bpp] if i >= bpp else 0
        if ft == 0:
            v = x
        elif ft == 1:
            v = x - a
        elif ft == 2:
            v = x - b
        elif ft == 3:
            v = x - (a + b) // 2
        else:
            v = x - paeth(a, b, c)
        out.append(v & 0xFF)
    return bytes(out)


ADAM = [(0, 0, 8, 8), (4, 0, 8, 8), (0, 4, 4, 8), (2, 0, 4, 4), (0, 2, 2, 4), (1, 0, 2, 2), (0, 1, 1, 2)]


def encode_png(w, h, ctype, depth, px, interlace, plte=None, trns=None, split_idat=False):
    """px[y][x] = tuple of native samples (len CHANNELS[ctype])."""
    ch = CHANNELS[ctype]
    bpp = max(1, ch * depth // 8)
    passes = ADAM if interlace else [(0, 0, 1, 1)]
    raw = bytearray()
    for pi, (xs, ys, dx, dy) in enumerate(passes):
        xs_list = list(range(xs, w, dx))
        ys_list = list(range(ys, h, dy))
        if not xs_list or not ys_list:
            continue  # an empty pass has no bytes at all, not even filter bytes
        prev = bytes(len(pack_samples([0] * (len(xs_list) * ch), depth)))
        for ri, y in enumerate(ys_list):
            samples = []
            for x in xs_list:
                samples.extend(px[y][x])
            cur = pack_samples(samples, depth)
            ft = (ri + pi) % 5  # every filter type gets used, on every kind of image
            raw.append(ft)
            raw += filter_row(ft, cur, prev, bpp)
            prev = cur
    z = zlib.compress(bytes(raw), 9)
    out = bytearray(b"\x89PNG\r\n\x1a\n")
    out += chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, depth, ctype, 0, 0, 1 if interlace else 0))
    out += chunk(b"gAMA", struct.pack(">I", 45455))  # an ancillary chunk that must be skipped
    if plte is not None:
        out += chunk(b"PLTE", b"".join(bytes(c) for c in plte))
    if trns is not None:
        out += chunk(b"tRNS", trns)
    if split_idat and len(z) > 8:
        half = len(z) // 2
        out += chunk(b"IDAT", z[:half]) + chunk(b"IDAT", z[half:])
    else:
        out += chunk(b"IDAT", z)
    out += chunk(b"IEND", b"")
    return bytes(out)


def to8(v, depth):
    if depth == 16:
        return (v * 255 + 32767) // 65535
    if depth == 8:
        return v
    return v * (255 // ((1 << depth) - 1))


def png_fixture(name, w, h, ctype, depth, interlace, seed, trns_kind=None):
    rnd = random.Random(seed)
    ch = CHANNELS[ctype]
    top = (1 << depth) - 1
    plte = None
    trns = None
    npal = 0
    if ctype == 3:
        npal = min(1 << depth, 1 + rnd.randrange(1 << depth) if trns_kind == "partial" else 1 << depth)
        npal = max(npal, 2) if depth > 1 else 2
        plte = [(rnd.randrange(256), rnd.randrange(256), rnd.randrange(256)) for _ in range(npal)]
        top = npal - 1
    px = [[tuple(rnd.randrange(top + 1) for _ in range(ch)) for _ in range(w)] for _ in range(h)]
    tkey = None
    if trns_kind and ctype == 0:
        tkey = px[0][0]
        trns = struct.pack(">H", tkey[0])
        for y in range(h):  # make sure some other pixels share the transparent value
            if rnd.randrange(3) == 0:
                px[y][rnd.randrange(w)] = tkey
    elif trns_kind and ctype == 2:
        tkey = px[0][0]
        trns = b"".join(struct.pack(">H", v) for v in tkey)
        for y in range(h):
            if rnd.randrange(3) == 0:
                px[y][rnd.randrange(w)] = tkey
    elif trns_kind and ctype == 3:
        k = 1 + rnd.randrange(npal) if trns_kind == "partial" else npal
        alphas = [rnd.randrange(256) for _ in range(k)]
        trns = bytes(alphas)
    data = encode_png(w, h, ctype, depth, px, interlace, plte, trns, split_idat=(seed % 3 == 0))
    exp = []
    for y in range(h):
        for x in range(w):
            s = px[y][x]
            if ctype == 0:
                g = to8(s[0], depth)
                a = 0 if tkey is not None and s == tkey else 255
                exp.append(premul(g, g, g, a))
            elif ctype == 2:
                a = 0 if tkey is not None and s == tkey else 255
                exp.append(premul(to8(s[0], depth), to8(s[1], depth), to8(s[2], depth), a))
            elif ctype == 3:
                r, g, b = plte[s[0]]
                a = trns[s[0]] if trns is not None and s[0] < len(trns) else 255
                exp.append(premul(r, g, b, a))
            elif ctype == 4:
                g = to8(s[0], depth)
                exp.append(premul(g, g, g, to8(s[1], depth)))
            else:
                exp.append(premul(*(to8(v, depth) for v in s)))
    return name, 1, w, h, data, exp


# ---------------------------------------------------------------- BMP ----------------------


def dib_header(size, w, h, bpp, comp, clr_used, masks):
    """masks = (r, g, b, a) written into V2+ headers; ignored for the 40-byte header."""
    hdr = struct.pack("<IiiHHIIiiII", size, w, h, 1, bpp, comp, 0, 2835, 2835, clr_used, 0)
    if size >= 52:
        hdr += struct.pack("<III", masks[0], masks[1], masks[2])
    if size >= 56:
        hdr += struct.pack("<I", masks[3])
    if size >= 108:
        hdr += struct.pack("<I", 0x73524742) + bytes(36) + bytes(12)  # "sRGB", endpoints, gamma
    if size >= 124:
        hdr += struct.pack("<IIII", 4, 0, 0, 0)
    assert len(hdr) == size, (len(hdr), size)
    return hdr


def chan(v, mask):
    if mask == 0:
        return None
    shift = (mask & -mask).bit_length() - 1
    bits = bin(mask >> shift).count("1")
    val = (v & mask) >> shift
    if bits >= 8:
        return val >> (bits - 8)
    m = (1 << bits) - 1
    return (val * 255 + m // 2) // m


def bmp_fixture(name, w, h, bpp, comp, dib, top_down, seed, clr_used=0, masks=(0, 0, 0, 0)):
    rnd = random.Random(seed)
    stride = ((w * bpp + 31) // 32) * 4
    rows = []  # rows in top-to-bottom order: (packed bytes, expected list)
    palette = []
    npal = 0
    if bpp <= 8:
        npal = clr_used if clr_used else 1 << bpp
        palette = [(rnd.randrange(256), rnd.randrange(256), rnd.randrange(256)) for _ in range(npal)]
    # masks in effect
    if comp in (3, 6):
        m = masks
        if dib == 40 and comp == 3:
            m = (masks[0], masks[1], masks[2], 0)
        if dib == 52:
            m = (masks[0], masks[1], masks[2], 0)
    elif bpp == 16:
        m = (0x7C00, 0x03E0, 0x001F, 0)
    else:
        m = (0x00FF0000, 0x0000FF00, 0x000000FF, 0)
    for y in range(h):
        buf = bytearray()
        exp = []
        if bpp <= 8:
            idxs = [rnd.randrange(npal) for _ in range(w)]
            cur, nb = 0, 0
            for i in idxs:
                cur = (cur << bpp) | i
                nb += bpp
                if nb == 8:
                    buf.append(cur)
                    cur, nb = 0, 0
            if nb:
                buf.append(cur << (8 - nb))
            for i in idxs:
                r, g, b = palette[i]
                exp.append(0xFF000000 | (r << 16) | (g << 8) | b)
        else:
            for _ in range(w):
                if bpp == 24:
                    b, g, r = rnd.randrange(256), rnd.randrange(256), rnd.randrange(256)
                    buf += bytes((b, g, r))
                    exp.append(0xFF000000 | (r << 16) | (g << 8) | b)
                    continue
                v = rnd.randrange(1 << bpp) if bpp == 16 else rnd.getrandbits(32)
                buf += struct.pack("<H" if bpp == 16 else "<I", v)
                r, g, b = chan(v, m[0]), chan(v, m[1]), chan(v, m[2])
                a = chan(v, m[3]) if m[3] else 255
                exp.append(premul(r, g, b, a))
        buf += bytes(stride - len(buf))
        rows.append((bytes(buf), exp))
    hdr_h = -h if top_down else h
    extra = b""
    maskbytes = b""
    if comp in (3, 6) and dib == 40:
        maskbytes = struct.pack("<III", masks[0], masks[1], masks[2])
        if comp == 6:
            maskbytes += struct.pack("<I", masks[3])
    pal_bytes = b"".join(bytes((b, g, r, 0)) for (r, g, b) in palette)
    dh = dib_header(dib, w, hdr_h, bpp, comp, clr_used, masks)
    off = 14 + dib + len(maskbytes) + len(pal_bytes)
    order = rows if top_down else rows[::-1]
    pix = b"".join(r[0] for r in order)
    total = off + len(pix)
    data = b"BM" + struct.pack("<IHHI", total, 0, 0, off) + dh + maskbytes + pal_bytes + pix
    exp_all = []
    for r in rows:  # expected pixels are always returned top row first
        exp_all.extend(r[1])
    return name, 2, w, h, data, exp_all


def all_fixtures():
    out = []
    sizes = [(1, 1), (3, 5), (9, 9), (33, 7)]
    seed = 1
    combos = [(0, d) for d in (1, 2, 4, 8, 16)] + [(2, 8), (2, 16)] + [(3, d) for d in (1, 2, 4, 8)] + [(4, 8), (4, 16), (6, 8), (6, 16)]
    for ctype, depth in combos:
        for (w, h) in sizes:
            for interlace in (0, 1):
                if interlace and (w, h) == (1, 1) and depth != 8:
                    continue
                seed += 1
                out.append(png_fixture("png_t%d_d%d_%dx%d%s" % (ctype, depth, w, h, "_i" if interlace else ""),
                                       w, h, ctype, depth, interlace, seed))
    for ctype, depth in [(0, 1), (0, 4), (0, 8), (0, 16), (2, 8), (2, 16), (3, 1), (3, 2), (3, 4), (3, 8)]:
        for (w, h) in [(9, 9), (33, 7)]:
            for interlace in (0, 1):
                seed += 1
                kind = "partial" if ctype == 3 else "yes"
                out.append(png_fixture("png_t%d_d%d_%dx%d%s_trns" % (ctype, depth, w, h, "_i" if interlace else ""),
                                       w, h, ctype, depth, interlace, seed, kind))
    # BMP
    for bpp, partial in ((1, 1), (4, 11), (8, 200)):
        for clr in (0, partial):
            for (w, h) in sizes:
                for td in (False, True):
                    if td and (w, h) not in ((3, 5), (9, 9)):
                        continue
                    seed += 1
                    out.append(bmp_fixture("bmp_p%d_c%d_%dx%d%s" % (bpp, clr, w, h, "_td" if td else ""),
                                           w, h, bpp, 0, 40, td, seed, clr_used=clr))
    cfgs = [
        ("b16_555", 16, 0, 40, (0, 0, 0, 0)),
        ("b16_565", 16, 3, 40, (0xF800, 0x07E0, 0x001F, 0)),
        ("b16_565_v4", 16, 3, 108, (0xF800, 0x07E0, 0x001F, 0)),
        ("b16_4444_v5", 16, 3, 124, (0x0F00, 0x00F0, 0x000F, 0xF000)),
        ("b24", 24, 0, 40, (0, 0, 0, 0)),
        ("b32_rgb", 32, 0, 40, (0, 0, 0, 0)),
        ("b32_bf888", 32, 3, 40, (0x00FF0000, 0x0000FF00, 0x000000FF, 0)),
        ("b32_abf", 32, 6, 40, (0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)),
        ("b32_v2", 32, 3, 52, (0x00FF0000, 0x0000FF00, 0x000000FF, 0)),
        ("b32_v3", 32, 3, 56, (0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)),
        ("b32_v4_10102", 32, 3, 108, (0x3FF00000, 0x000FFC00, 0x000003FF, 0xC0000000)),
        ("b32_v5_abf", 32, 6, 124, (0x000000FF, 0x0000FF00, 0x00FF0000, 0xFF000000)),
        ("b32_v4_rgb_junkmasks", 32, 0, 108, (0x0000FF00, 0x00FF0000, 0xFF000000, 0x000000FF)),
        ("b32_bf_full_r", 32, 3, 40, (0xFFFFFF00, 0x000000F0, 0x0000000F, 0)),
    ]
    for cname, bpp, comp, dib, masks in cfgs:
        for (w, h) in sizes:
            for td in (False, True):
                if td and (w, h) != (3, 5):
                    continue
                seed += 1
                out.append(bmp_fixture("bmp_%s_%dx%d%s" % (cname, w, h, "_td" if td else ""),
                                       w, h, bpp, comp, dib, td, seed, masks=masks))
    return out


def main():
    blob = bytearray()
    fixtures = all_fixtures()
    for name, kind, w, h, data, exp in fixtures:
        assert len(exp) == w * h, name
        nb = name.encode()
        blob += struct.pack("<H", len(nb)) + nb + struct.pack("<BIII", kind, w, h, len(data)) + data
        blob += b"".join(struct.pack("<I", v) for v in exp)
    with open(os.path.join(HERE, "decode-fixtures.z"), "wb") as f:
        f.write(zlib.compress(bytes(blob), 9))
    print(len(fixtures), "fixtures,", len(blob), "bytes raw")


if __name__ == "__main__":
    main()
