#!/usr/bin/env python3
"""Generates tests/data/gfx/jpeg-fixtures.z for libs/gfx's JPEG decoder tests (M12.7, D-160..D-165).

An independent JPEG *encoder* written from ITU-T T.81 (Python stdlib only; ARCHITECTURE §0's
host-tool exception) writes many files across frame types, sampling layouts, scan scripts, Huffman
tables, restart intervals and marker variants. The expected pixels are NOT obtained by parsing the
bitstream: they are computed from the quantized coefficient arrays the encoder itself started
from, through an exact integer model of the decoder pipeline (D-161): dequantize, clamp to int16,
the LLM "islow" integer IDCT, replicated chroma upsampling (sx = x*Hc//Hmax), libjpeg's 16-bit
fixed-point YCbCr conversion. So Huffman decoding, MCU layout, progression and restart handling in
the C decoder are checked against something other than the C decoder.

Container: u32 LE rawLen, then zlib(raw). raw is a sequence of records:
  u16 nameLen, name, i32 status (0, or the expected Status of the decode), u8 flags (bit0: the
  expected field is a CRC-32 of the pixel bytes instead of the pixels), u32 width, u32 height,
  u32 dataLen, data, then (only when status == 0) width*height LE u32 opaque ARGB pixels, or the
  4-byte CRC-32 (zlib.crc32 of those pixel bytes) when flags bit0 is set.
Names are  jg_<group>__<variant>  : every variant of a group encodes the very same coefficients, so
the C decoder must give identical pixels for all of them (the test checks that too).

Run manually (`python3 tests/data/gfx/gen_jpeg.py`); the output is checked in, not regenerated by
the build.
"""
import math
import os
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))

STATUS_OK, STATUS_INVALID, STATUS_UNSUPPORTED = 0, -1, -4


class Rng:
    """xorshift32, so fixtures never depend on a Python version's `random`."""

    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF or 0x9E3779B9

    def next(self):
        x = self.s
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= x >> 17
        x ^= (x << 5) & 0xFFFFFFFF
        self.s = x
        return x

    def below(self, n):
        return self.next() % n

    def range(self, lo, hi):  # inclusive
        return lo + self.below(hi - lo + 1)


# ------------------------------------------------------------------ zigzag (T.81 Figure A.6) --


def make_zigzag():
    order = []
    for s in range(15):
        diag = [(y, s - y) for y in range(8) if 0 <= s - y < 8]  # (row, col)
        if s % 2 == 0:
            diag.reverse()  # even diagonals run bottom-left to top-right... see check below
        order.extend(r * 8 + c for r, c in diag)
    return order


ZZ = make_zigzag()
assert ZZ[:10] == [0, 1, 8, 16, 9, 2, 3, 10, 17, 24] and ZZ[-1] == 63 and sorted(ZZ) == list(range(64))

# ------------------------------------------------------------------ exact decoder model --------

FIX = {
    "0_298": 2446, "0_390": 3196, "0_541": 4433, "0_765": 6270, "0_899": 7373, "1_175": 9633,
    "1_501": 12299, "1_847": 15137, "1_961": 16069, "2_053": 16819, "2_562": 20995, "3_072": 25172,
}
for _name, _val in (("0_298", 0.298631336), ("0_390", 0.390180644), ("0_541", 0.541196100),
                    ("0_765", 0.765366865), ("0_899", 0.899976223), ("1_175", 1.175875602),
                    ("1_501", 1.501321110), ("1_847", 1.847759065), ("1_961", 1.961570560),
                    ("2_053", 2.053119869), ("2_562", 2.562915447), ("3_072", 3.072711026)):
    assert FIX[_name] == round(_val * 8192), _name


def descale(x, n):
    return (x + (1 << (n - 1))) >> n  # Python's >> is arithmetic on negatives


def idct_1d(v):
    z1 = (v[2] + v[6]) * 4433
    t2 = z1 - v[6] * 15137
    t3 = z1 + v[2] * 6270
    t0 = (v[0] + v[4]) * 8192
    t1 = (v[0] - v[4]) * 8192
    t10, t13, t11, t12 = t0 + t3, t0 - t3, t1 + t2, t1 - t2
    o0, o1, o2, o3 = v[7], v[5], v[3], v[1]
    z1, z2, z3, z4 = o0 + o3, o1 + o2, o0 + o2, o1 + o3
    z5 = (z3 + z4) * 9633
    o0 *= 2446
    o1 *= 16819
    o2 *= 25172
    o3 *= 12299
    z1 *= -7373
    z2 *= -20995
    z3 *= -16069
    z4 *= -3196
    z3 += z5
    z4 += z5
    o0 += z1 + z3
    o1 += z2 + z4
    o2 += z2 + z3
    o3 += z1 + z4
    return [t10 + o3, t11 + o2, t12 + o1, t13 + o0, t13 - o0, t12 - o1, t11 - o2, t10 - o3]


def clamp(x, lo, hi):
    return lo if x < lo else hi if x > hi else x


def idct_block(coef, q):
    """coef, q: natural order. Returns 64 clamped 0..255 samples (row-major)."""
    d = [clamp(coef[i] * q[i], -32768, 32767) for i in range(64)]
    ws = [0] * 64
    for c in range(8):
        out = idct_1d([d[8 * i + c] for i in range(8)])
        for i in range(8):
            ws[8 * i + c] = descale(out[i], 11)
    res = [0] * 64
    for r in range(8):
        out = idct_1d(ws[8 * r:8 * r + 8])
        for i in range(8):
            res[8 * r + i] = clamp(descale(out[i], 18) + 128, 0, 255)
    return res


def ycc_to_rgb(y, cb, cr):
    cb -= 128
    cr -= 128
    r = y + ((91881 * cr + 32768) >> 16)
    g = y + ((-22554 * cb - 46802 * cr + 32768) >> 16)
    b = y + ((116130 * cb + 32768) >> 16)
    return clamp(r, 0, 255), clamp(g, 0, 255), clamp(b, 0, 255)


def ceil_div(a, b):
    return (a + b - 1) // b


class Frame:
    """A frame's parameters plus quantized coefficients: coefs[c][by][bx] -> 64 ints, natural
    order, on the padded block grid (bw = mcusX*Hc by bh = mcusY*Vc)."""

    def __init__(self, w, h, comps, qtables, colorspace):
        self.w, self.h = w, h
        self.comps = comps  # list of dicts: id, h, v, tq
        self.qtables = qtables  # id -> 64 ints (natural order) as latched by the FIRST scan
        self.colorspace = colorspace  # 'gray' | 'ycc' | 'rgb'
        self.hmax = max(c["h"] for c in comps)
        self.vmax = max(c["v"] for c in comps)
        self.mcusx = ceil_div(w, 8 * self.hmax)
        self.mcusy = ceil_div(h, 8 * self.vmax)
        for c in comps:
            c["compw"] = ceil_div(w * c["h"], self.hmax)
            c["comph"] = ceil_div(h * c["v"], self.vmax)
            c["nbx"] = ceil_div(c["compw"], 8)
            c["nby"] = ceil_div(c["comph"], 8)
            c["bw"] = self.mcusx * c["h"]
            c["bh"] = self.mcusy * c["v"]
        self.coefs = None
        self.latched_q = None  # per-component q actually used for the model (set by the encoder)

    def expected(self, qs=None):
        """Model output: list of h rows of w opaque ARGB pixels. qs: per-component natural q."""
        qs = qs or [self.qtables[c["tq"]] for c in self.comps]
        cache = {}
        planes = []
        for ci, c in enumerate(self.comps):
            pw = c["nbx"] * 8
            ph = c["nby"] * 8
            plane = [[0] * pw for _ in range(ph)]
            for by in range(c["nby"]):
                for bx in range(c["nbx"]):
                    blk = self.coefs[ci][by][bx]
                    key = (tuple(blk), tuple(qs[ci]))
                    px = cache.get(key)
                    if px is None:
                        px = cache[key] = idct_block(blk, qs[ci])
                    for r in range(8):
                        plane[by * 8 + r][bx * 8:bx * 8 + 8] = px[8 * r:8 * r + 8]
            planes.append(plane)
        rows = []
        for y in range(self.h):
            row = []
            for x in range(self.w):
                s = []
                for ci, c in enumerate(self.comps):
                    s.append(planes[ci][y * c["v"] // self.vmax][x * c["h"] // self.hmax])
                if self.colorspace == "gray":
                    r = g = b = s[0]
                elif self.colorspace == "rgb":
                    r, g, b = s
                else:
                    r, g, b = ycc_to_rgb(*s)
                row.append(0xFF000000 | (r << 16) | (g << 8) | b)
            rows.append(row)
        return rows


# ------------------------------------------------------------------ forward DCT + images -------

COS = [[math.cos((2 * x + 1) * u * math.pi / 16) for x in range(8)] for u in range(8)]


def fdct_block(px):
    """px: 64 samples (already level-shifted by -128). Returns 64 float coefficients (natural)."""
    tmp = [0.0] * 64
    for y in range(8):
        for u in range(8):
            tmp[8 * y + u] = sum(px[8 * y + x] * COS[u][x] for x in range(8))
    out = [0.0] * 64
    for u in range(8):
        for v in range(8):
            s = sum(tmp[8 * y + u] * COS[v][y] for y in range(8))
            cu = math.sqrt(0.5) if u == 0 else 1.0
            cv = math.sqrt(0.5) if v == 0 else 1.0
            out[8 * v + u] = 0.25 * cu * cv * s
    return out


def natural_rgb(w, h, seed=1):
    """A smooth-plus-edges test picture: gradients, a disc, diagonal stripes, some noise."""
    rng = Rng(seed)
    img = []
    for y in range(h):
        row = []
        for x in range(w):
            fx, fy = x / max(w - 1, 1), y / max(h - 1, 1)
            r = 40 + 180 * fx
            g = 30 + 190 * fy
            b = 200 - 120 * (fx + fy) / 2
            dx, dy = x - w * 0.6, y - h * 0.4
            if dx * dx + dy * dy < (min(w, h) * 0.3) ** 2:
                r, g, b = 230, 60 + 100 * fx, 40
            if (x + y) % 16 < 3:
                r, g, b = 255 - r, 255 - g, 255 - b
            n = rng.below(9) - 4
            row.append(tuple(clamp(int(round(v)) + n, 0, 255) for v in (r, g, b)))
        img.append(row)
    return img


def rgb_to_ycc(r, g, b):
    y = 0.299 * r + 0.587 * g + 0.114 * b
    cb = -0.168736 * r - 0.331264 * g + 0.5 * b + 128
    cr = 0.5 * r - 0.418688 * g - 0.081312 * b + 128
    return y, cb, cr


def make_natural(w, h, layout, colorspace, q, seed=1, tqs=None):
    """layout: list of (h, v). Returns a Frame with FDCT'd, quantized coefficients. q: natural q
    per component (list of 64-lists) or a single one applied to all."""
    ncomp = len(layout)
    tqs = tqs or [0] + [1] * (ncomp - 1)
    ids = {"gray": [1], "ycc": [1, 2, 3], "rgb": [1, 2, 3]}[colorspace]
    comps = [{"id": ids[i], "h": layout[i][0], "v": layout[i][1], "tq": tqs[i]} for i in range(ncomp)]
    qtables = {}
    for i, c in enumerate(comps):
        qtables[c["tq"]] = q[i] if isinstance(q[0], list) else q
    f = Frame(w, h, comps, qtables, colorspace)
    img = natural_rgb(w, h, seed)
    src = []  # per-component full-resolution float planes
    for ci in range(ncomp):
        src.append([[0.0] * w for _ in range(h)])
    for y in range(h):
        for x in range(w):
            r, g, b = img[y][x]
            if colorspace == "gray":
                vals = (0.299 * r + 0.587 * g + 0.114 * b,)
            elif colorspace == "rgb":
                vals = (r, g, b)
            else:
                vals = rgb_to_ycc(r, g, b)
            for ci in range(ncomp):
                src[ci][y][x] = vals[ci]
    f.coefs = []
    for ci, c in enumerate(comps):
        # component plane: box-average the source pixels that map onto each sample
        pw, ph = c["bw"] * 8, c["bh"] * 8
        plane = [[0.0] * pw for _ in range(ph)]
        ys_of = [[y for y in range(h) if y * c["v"] // f.vmax == cy] for cy in range(c["comph"])]
        xs_of = [[x for x in range(w) if x * c["h"] // f.hmax == cx] for cx in range(c["compw"])]
        for cy in range(c["comph"]):
            for cx in range(c["compw"]):
                pts = [src[ci][y][x] for y in ys_of[cy] for x in xs_of[cx]]
                # fractional ratios leave samples nothing maps to (D-161); any value will do
                plane[cy][cx] = sum(pts) / len(pts) if pts else plane[cy][max(cx - 1, 0)]
        for cy in range(ph):  # edge replication into the padded area
            for cx in range(pw):
                plane[cy][cx] = plane[min(cy, c["comph"] - 1)][min(cx, c["compw"] - 1)]
        qq = qtables[c["tq"]]
        blocks = []
        for by in range(c["bh"]):
            row = []
            for bx in range(c["bw"]):
                px = [plane[by * 8 + r][bx * 8 + x] - 128 for r in range(8) for x in range(8)]
                co = fdct_block(px)
                blk = [int(round(co[i] / qq[i])) for i in range(64)]
                assert all(abs(blk[i] * qq[i]) < 32000 for i in range(64))
                assert abs(blk[0]) <= 1023 and all(abs(blk[i]) <= 1023 for i in range(1, 64))
                row.append(blk)
            blocks.append(row)
        f.coefs.append(blocks)
    return f


def make_random(w, h, layout, colorspace, q, seed, tqs=None):
    """Random quantized coefficients hitting every DC category 0..11 (as differences), AC sizes
    1..10, long zero runs (ZRL) and k = 63, on every block of the padded grid."""
    rng = Rng(seed)
    ncomp = len(layout)
    tqs = tqs or [0] + [1] * (ncomp - 1)
    ids = {"gray": [1], "ycc": [1, 2, 3], "rgb": [1, 2, 3]}[colorspace]
    comps = [{"id": ids[i], "h": layout[i][0], "v": layout[i][1], "tq": tqs[i]} for i in range(ncomp)]
    qtables = {}
    for i, c in enumerate(comps):
        qtables[c["tq"]] = q[i] if isinstance(q[0], list) else q
    f = Frame(w, h, comps, qtables, colorspace)
    f.coefs = []
    for ci, c in enumerate(comps):
        blocks = []
        for by in range(c["bh"]):
            row = []
            for bx in range(c["bw"]):
                blk = [0] * 64
                cat = rng.below(12)
                if cat == 11:
                    blk[0] = 1023 if (bx + by) % 2 == 0 else -1023
                elif cat == 0:
                    blk[0] = 0
                else:
                    mag = rng.range(1 << (cat - 1), min((1 << cat) - 1, 1023))
                    blk[0] = mag if rng.below(2) else -mag
                mode = rng.below(4)
                if mode == 1:  # sparse with long runs
                    for _ in range(rng.range(1, 4)):
                        k = rng.range(1, 63)
                        blk[ZZ[k]] = rng.range(1, 3) * (1 if rng.below(2) else -1)
                elif mode == 2:  # dense low frequencies, mixed sizes
                    for k in range(1, rng.range(2, 30)):
                        s = rng.range(0, 10)
                        if s:
                            mag = rng.range(1 << (s - 1), (1 << s) - 1)
                            blk[ZZ[k]] = mag if rng.below(2) else -mag
                elif mode == 3:  # last coefficient set
                    blk[ZZ[63]] = rng.range(1, 1023) * (1 if rng.below(2) else -1)
                    blk[ZZ[rng.range(1, 62)]] = rng.range(1, 60)
                row.append(blk)
            blocks.append(row)
        f.coefs.append(blocks)
    qq = qtables
    assert all(abs(cf * qq[c["tq"]][i]) < 32768 for ci, c in enumerate(comps)
               for r in f.coefs[ci] for blk in r for i, cf in enumerate(blk))
    return f


def flat_q(v):
    return [v] * 64


def std_q(scale=1):
    """A JPEG-ish quantization table (natural order), coarser at high frequencies."""
    return [max(1, (4 + (i // 8) + (i % 8)) * scale // 2) for i in range(64)]


# ------------------------------------------------------------------ Huffman tables -------------


def optimal_table(freq_in, pad=0):
    """T.81 Annex K.2/K.3 (Figures K.1, K.2): code lengths limited to 16, the reserved all-ones
    code kept free by a pseudo-symbol 256. Returns (bits[1..16], huffval)."""
    freq = list(freq_in) + [0] * (257 - len(freq_in))
    freq[256] = 1
    codesize = [0] * 257
    others = [-1] * 257
    while True:
        c1, v = -1, 1 << 60
        for i in range(257):
            if freq[i] and freq[i] <= v:
                v, c1 = freq[i], i
        c2, v = -1, 1 << 60
        for i in range(257):
            if freq[i] and freq[i] <= v and i != c1:
                v, c2 = freq[i], i
        if c2 < 0:
            break
        freq[c1] += freq[c2]
        freq[c2] = 0
        codesize[c1] += 1
        while others[c1] >= 0:
            c1 = others[c1]
            codesize[c1] += 1
        others[c1] = c2
        codesize[c2] += 1
        while others[c2] >= 0:
            c2 = others[c2]
            codesize[c2] += 1
    bits = [0] * 64
    for i in range(257):
        if codesize[i]:
            bits[codesize[i]] += 1
    for i in range(63, 16, -1):
        while bits[i] > 0:
            j = i - 2
            while bits[j] == 0:
                j -= 1
            bits[i] -= 2
            bits[i - 1] += 1
            bits[j + 1] += 2
            bits[j] -= 1
    i = 16
    while bits[i] == 0:
        i -= 1
    bits[i] -= 1
    vals = []
    for length in range(1, 33):
        for s in range(256):
            if codesize[s] == length:
                vals.append(s)
    return bits[1:17], vals


def skewed_table(used):
    """A table with a 16-bit code: exponentially skewed frequencies over `used` plus padding
    symbols (unused ones are legal in a DHT) until there are at least 20."""
    syms = sorted(set(used))
    extra = [s for s in range(0x11, 0x100) if s not in syms]
    while len(syms) < 20:
        syms.append(extra.pop(0))
    freq = [0] * 256
    for rank, s in enumerate(sorted(syms)):
        freq[s] = 1 << min(rank, 22)  # bounded so the unlimited tree stays <= 32 deep
    bits, vals = optimal_table(freq)
    assert max(i + 1 for i, n in enumerate(bits) if n) == 16, bits
    return bits, vals


def flat_table(used):
    syms = sorted(set(used))
    length = 1
    while (1 << length) < len(syms) + 1:
        length += 1
    bits = [0] * 16
    bits[length - 1] = len(syms)
    return bits, syms


def canonical_codes(bits, vals):
    """T.81 Annex C: symbol -> (code, length)."""
    codes = {}
    code, k = 0, 0
    for length in range(1, 17):
        for _ in range(bits[length - 1]):
            codes[vals[k]] = (code, length)
            code += 1
            k += 1
        code <<= 1
    return codes


# ------------------------------------------------------------------ bit writer + scans ---------


class BitWriter:
    def __init__(self):
        self.out = bytearray()
        self.acc = 0
        self.n = 0

    def put(self, value, nbits):
        if nbits == 0:
            return
        self.acc = (self.acc << nbits) | (value & ((1 << nbits) - 1))
        self.n += nbits
        while self.n >= 8:
            b = (self.acc >> (self.n - 8)) & 0xFF
            self.out.append(b)
            if b == 0xFF:
                self.out.append(0)
            self.n -= 8
        self.acc &= (1 << self.n) - 1

    def flush(self):  # pad with 1 bits to a byte boundary
        if self.n:
            self.put((1 << (8 - self.n)) - 1, 8 - self.n)


def category(v):
    return abs(v).bit_length()


def extra_bits(v, n):
    return v if v >= 0 else v + (1 << n) - 1


def scan_mcus(f, comps):
    """The MCU list of a scan over the component indexes `comps`: each MCU is a list of
    (component, bx, by)."""
    mcus = []
    if len(comps) > 1:
        for my in range(f.mcusy):
            for mx in range(f.mcusx):
                m = []
                for ci in comps:
                    c = f.comps[ci]
                    for j in range(c["v"]):
                        for i in range(c["h"]):
                            m.append((ci, mx * c["h"] + i, my * c["v"] + j))
                mcus.append(m)
    else:
        c = f.comps[comps[0]]
        for by in range(c["nby"]):
            for bx in range(c["nbx"]):
                mcus.append([(comps[0], bx, by)])
    return mcus


def sequential_events(f, scan, ri):
    """Events for a sequential scan. ('h', class, table, symbol), ('b', value, nbits), ('rst',)."""
    ev = []
    pred = {ci: 0 for ci in scan["comps"]}
    for n, mcu in enumerate(scan_mcus(f, scan["comps"])):
        if ri and n and n % ri == 0:
            ev.append(("rst",))
            pred = {ci: 0 for ci in scan["comps"]}
        for ci, bx, by in mcu:
            blk = f.coefs[ci][by][bx]
            dt, at = scan["dctab"][ci], scan["actab"][ci]
            diff = blk[0] - pred[ci]
            pred[ci] = blk[0]
            t = category(diff)
            assert t <= 11
            ev.append(("h", 0, dt, t))
            if t:
                ev.append(("b", extra_bits(diff, t), t))
            run = 0
            for k in range(1, 64):
                v = blk[ZZ[k]]
                if v == 0:
                    run += 1
                    continue
                while run > 15:
                    ev.append(("h", 1, at, 0xF0))
                    run -= 16
                s = category(v)
                assert s <= 10
                ev.append(("h", 1, at, (run << 4) | s))
                ev.append(("b", extra_bits(v, s), s))
                run = 0
            if run:
                ev.append(("h", 1, at, 0x00))
    return ev


def build_tables(ev, mode):
    """Per (class, id) Huffman tables from the events' symbol statistics."""
    used = {}
    for e in ev:
        if e[0] == "h":
            used.setdefault((e[1], e[2]), []).append(e[3])
    tables = {}
    for key, syms in used.items():
        freq = [0] * 256
        for s in syms:
            freq[s] += 1
        m = mode(key) if callable(mode) else mode
        if m == "skew":
            tables[key] = skewed_table(syms)
        elif m == "flat":
            tables[key] = flat_table(syms)
        else:
            tables[key] = optimal_table(freq)
    return tables


def write_entropy(ev, tables, ri):
    codes = {k: canonical_codes(*t) for k, t in tables.items()}
    bw = BitWriter()
    rst = 0
    for e in ev:
        if e[0] == "h":
            code, length = codes[(e[1], e[2])][e[3]]
            bw.put(code, length)
        elif e[0] == "b":
            bw.put(e[1], e[2])
        else:
            bw.flush()
            bw.out += bytes([0xFF, 0xD0 + (rst & 7)])
            rst += 1
    bw.flush()
    return bytes(bw.out)


# ------------------------------------------------------------------ markers + assembly ---------


def seg(marker, payload):
    return bytes([0xFF, marker]) + struct.pack(">H", len(payload) + 2) + payload


def dqt_segment(tables, use16):
    p = bytearray()
    for tid, q in sorted(tables.items()):
        if use16:
            p.append(0x10 | tid)
            for k in range(64):
                p += struct.pack(">H", q[ZZ[k]])
        else:
            p.append(tid)
            for k in range(64):
                p.append(q[ZZ[k]])
    return seg(0xDB, bytes(p))


def dht_segment(tables):
    p = bytearray()
    for (cls, tid), (bits, vals) in sorted(tables.items()):
        p.append((cls << 4) | tid)
        p += bytes(bits)
        p += bytes(vals)
    return seg(0xC4, bytes(p))


def encode(f, scans, opt=None):
    """scans: list of dicts {comps, ss, se, ah, al, dctab{ci:id}, actab{ci:id}, dqt: {id: q}?}.
    opt: sof (0/1/2), ri, jfif, adobe (None/0/1), dqt16, tabmode, fill, junk, junk_rst."""
    opt = opt or {}
    sof = opt.get("sof", 0)
    ri = opt.get("ri", 0)
    fill = opt.get("fill", False)
    out = bytearray(b"\xff\xd8")

    def add(b):
        if fill:
            out.extend(b"\xff\xff")
        out.extend(b)

    if opt.get("jfif"):
        add(seg(0xE0, b"JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"))
    if opt.get("adobe") is not None:
        add(seg(0xEE, b"Adobe\x00\x64\x00\x00\x00\x00" + bytes([opt["adobe"]])))
    if opt.get("comment"):
        add(seg(0xFE, b"generated by gen_jpeg.py"))
    qcur = {}
    for c in f.comps:
        qcur[c["tq"]] = f.qtables[c["tq"]]
    add(dqt_segment(qcur, opt.get("dqt16", False)))
    sofp = bytearray([8]) + struct.pack(">HH", f.h, f.w) + bytes([len(f.comps)])
    for c in f.comps:
        sofp += bytes([c["id"], (c["h"] << 4) | c["v"], c["tq"]])
    add(seg(0xC0 + sof, bytes(sofp)))
    latched = [None] * len(f.comps)
    for si, s in enumerate(scans):
        if "dqt" in s:  # a DQT redefinition between scans
            qcur.update(s["dqt"])
            add(dqt_segment(s["dqt"], opt.get("dqt16", False)))
        for ci in s["comps"]:
            if latched[ci] is None:
                latched[ci] = list(qcur[f.comps[ci]["tq"]])
        if "dri" in s:
            ri = s["dri"]
        add(seg(0xDD, struct.pack(">H", ri)))
        ev = s["events"](f, s, ri) if callable(s.get("events")) else sequential_events(f, s, ri)
        tables = build_tables(ev, s.get("tabmode", opt.get("tabmode", "opt")))
        if tables:
            add(dht_segment(tables))
        sp = bytearray([len(s["comps"])])
        for ci in s["comps"]:
            sp += bytes([f.comps[ci]["id"], (s["dctab"].get(ci, 0) << 4) | s["actab"].get(ci, 0)])
        sp += bytes([s["ss"], s["se"], (s["ah"] << 4) | s["al"]])
        add(seg(0xDA, bytes(sp)))
        data = write_entropy(ev, tables, ri)
        if opt.get("junk") or opt.get("junk_rst"):
            data = inject_junk(data, opt.get("junk_rst", False))
        out.extend(data)
    if fill:
        out.extend(b"\xff\xff")
    out.extend(b"\xff\xd9")
    return bytes(out), latched


def inject_junk(data, before_rst_only):
    """Extraneous bytes (no 0xFF) between the end of entropy data and the marker that follows."""
    out = bytearray()
    i = 0
    while i < len(data):
        if data[i] == 0xFF and data[i + 1] != 0:
            out += b"\x12\x34" + data[i:i + 2]
            i += 2
        else:
            out.append(data[i])
            i += 1
    if not before_rst_only:
        out += b"\x55"
    return bytes(out)


def seq_scans(f, script, dctab=None, actab=None):
    """script: 'inter' (one interleaved scan), 'split' (one scan per component), 'ycc' (Y, then
    Cb+Cr), 'nonint' alias of split."""
    n = len(f.comps)
    dctab = dctab or {ci: (0 if ci == 0 else 1) for ci in range(n)}
    actab = actab or dict(dctab)
    groups = {"inter": [list(range(n))], "split": [[i] for i in range(n)], "nonint": [[i] for i in range(n)],
              "ycc": [[0], [1, 2]] if n == 3 else [list(range(n))]}[script]
    return [{"comps": g, "ss": 0, "se": 63, "ah": 0, "al": 0,
             "dctab": {ci: dctab[ci] for ci in g}, "actab": {ci: actab[ci] for ci in g}} for g in groups]



# ------------------------------------------------------------------ progressive scans ----------


class EobState:
    def __init__(self):
        self.run = 0
        self.be = []  # buffered correction bits belonging to the pending EOB run


def flush_eobrun(st, ev, at):
    if st.run > 0:
        nb = st.run.bit_length() - 1
        ev.append(("h", 1, at, nb << 4))
        if nb:
            ev.append(("b", st.run & ((1 << nb) - 1), nb))
        for bit in st.be:
            ev.append(("b", bit, 1))
        st.run = 0
        st.be = []


def ac_first_block(blk, ss, se, al, at, st, ev):
    r = 0
    for k in range(ss, se + 1):
        v = blk[ZZ[k]]
        temp = ((-v) >> al) if v < 0 else (v >> al)
        if temp == 0:
            r += 1
            continue
        flush_eobrun(st, ev, at)
        while r > 15:
            ev.append(("h", 1, at, 0xF0))
            r -= 16
        nb = temp.bit_length()
        assert nb <= 10
        ev.append(("h", 1, at, (r << 4) | nb))
        ev.append(("b", temp if v >= 0 else (~temp) & ((1 << nb) - 1), nb))
        r = 0
    if r > 0:
        st.run += 1
        if st.run == 0x7FFF:
            flush_eobrun(st, ev, at)


def ac_refine_block(blk, ss, se, al, at, st, ev):
    absv = {}
    eob = 0
    for k in range(ss, se + 1):
        temp = abs(blk[ZZ[k]]) >> al
        absv[k] = temp
        if temp == 1:
            eob = k
    r = 0
    br = []
    for k in range(ss, se + 1):
        temp = absv[k]
        if temp == 0:
            r += 1
            continue
        while r > 15 and k <= eob:
            flush_eobrun(st, ev, at)
            ev.append(("h", 1, at, 0xF0))
            r -= 16
            for bit in br:
                ev.append(("b", bit, 1))
            br = []
        if temp > 1:
            br.append(temp & 1)
            continue
        flush_eobrun(st, ev, at)
        ev.append(("h", 1, at, (r << 4) | 1))
        ev.append(("b", 1 if blk[ZZ[k]] >= 0 else 0, 1))
        for bit in br:
            ev.append(("b", bit, 1))
        br = []
        r = 0
    if r > 0 or br:
        st.run += 1
        st.be.extend(br)
        if st.run == 0x7FFF:
            flush_eobrun(st, ev, at)


def progressive_events(f, scan, ri):
    ss, se, ah, al = scan["ss"], scan["se"], scan["ah"], scan["al"]
    ev = []
    if ss == 0:  # DC scan (may be interleaved)
        pred = {ci: 0 for ci in scan["comps"]}
        for n, mcu in enumerate(scan_mcus(f, scan["comps"])):
            if ri and n and n % ri == 0:
                ev.append(("rst",))
                pred = {ci: 0 for ci in scan["comps"]}
            for ci, bx, by in mcu:
                v = f.coefs[ci][by][bx][0]
                if ah == 0:
                    sv = v >> al
                    diff = sv - pred[ci]
                    pred[ci] = sv
                    t = category(diff)
                    assert t <= 11
                    ev.append(("h", 0, scan["dctab"][ci], t))
                    if t:
                        ev.append(("b", extra_bits(diff, t), t))
                else:
                    ev.append(("b", (v >> al) & 1, 1))
    else:
        assert len(scan["comps"]) == 1
        ci = scan["comps"][0]
        at = scan["actab"][ci]
        st = EobState()
        for n, mcu in enumerate(scan_mcus(f, scan["comps"])):
            if ri and n and n % ri == 0:
                flush_eobrun(st, ev, at)
                ev.append(("rst",))
            _, bx, by = mcu[0]
            blk = f.coefs[ci][by][bx]
            (ac_first_block if ah == 0 else ac_refine_block)(blk, ss, se, al, at, st, ev)
        flush_eobrun(st, ev, at)
    return ev


def prog_scans(f, script, ids=None):
    n = len(f.comps)
    ids = ids or {ci: (0 if ci == 0 else 1) for ci in range(n)}

    def sc(comps, ss, se, ah, al):
        return {"comps": comps, "ss": ss, "se": se, "ah": ah, "al": al, "events": progressive_events,
                "dctab": {ci: ids[ci] for ci in comps}, "actab": {ci: ids[ci] for ci in comps}}

    allc = list(range(n))
    blocks = sum(c["h"] * c["v"] for c in f.comps)
    dcgroups = [allc] if blocks <= 10 else [[ci] for ci in allc]
    out = []
    if script == "default":  # libjpeg's simple progression
        for g in dcgroups:
            out.append(sc(g, 0, 0, 0, 1))
        out.append(sc([0], 1, 5, 0, 2))
        for ci in reversed(allc[1:]):
            out.append(sc([ci], 1, 63, 0, 1))
        out.append(sc([0], 6, 63, 0, 2))
        out.append(sc([0], 1, 63, 2, 1))
        for g in dcgroups:
            out.append(sc(g, 0, 0, 1, 0))
        for ci in reversed(allc[1:]):
            out.append(sc([ci], 1, 63, 1, 0))
        out.append(sc([0], 1, 63, 1, 0))
    elif script == "deep":  # successive approximation 3 -> 2 -> 1 -> 0, DC per component
        for ci in allc:
            out.append(sc([ci], 0, 0, 0, 3))
        for ci in allc:
            out.append(sc([ci], 1, 63, 0, 3))
        for a in (3, 2, 1):
            for ci in allc:
                out.append(sc([ci], 0, 0, a, a - 1))
            for ci in allc:
                out.append(sc([ci], 1, 63, a, a - 1))
    elif script == "bands":  # spectral selection only, odd bands
        for g in dcgroups:
            out.append(sc(g, 0, 0, 0, 0))
        for ci in allc:
            for lo, hi in ((1, 1), (2, 9), (10, 63)):
                out.append(sc([ci], lo, hi, 0, 0))
    else:
        raise ValueError(script)
    return out


def prog_variants(f, grp, lname, scripts=("default", "deep", "bands"), extra=()):
    for sc in scripts:
        data, lat = encode(f, prog_scans(f, sc), {"sof": 2, "jfif": True})
        add_record("jg_%s__prog_%s" % (grp, sc), data, STATUS_OK, f)
    for ri in extra:
        data, lat = encode(f, prog_scans(f, "default"), {"sof": 2, "ri": ri})
        add_record("jg_%s__prog_default_ri%d" % (grp, ri), data, STATUS_OK, f)


# ------------------------------------------------------------------ fixtures -------------------

records = []


def add_record(name, data, status, frame=None, qs=None, crc=False, wh=(0, 0)):
    w, h = (frame.w, frame.h) if frame else wh
    rec = bytearray()
    nm = name.encode()
    rec += struct.pack("<H", len(nm)) + nm
    rec += struct.pack("<iBIII", status, 1 if crc else 0, w, h, len(data)) + data
    if status == STATUS_OK:
        rows = frame.expected(qs)
        px = b"".join(struct.pack("<I", p) for row in rows for p in row)
        rec += struct.pack("<I", zlib.crc32(px) & 0xFFFFFFFF) if crc else px
    records.append(bytes(rec))


LAYOUTS = {
    "gray1": ("gray", [(1, 1)]),
    "gray2x2": ("gray", [(2, 2)]),
    "c444": ("ycc", [(1, 1)] * 3),
    "c422": ("ycc", [(2, 1), (1, 1), (1, 1)]),
    "c420": ("ycc", [(2, 2), (1, 1), (1, 1)]),
    "c440": ("ycc", [(1, 2), (1, 1), (1, 1)]),
    "c411": ("ycc", [(4, 1), (1, 1), (1, 1)]),
    "c311": ("ycc", [(3, 1), (1, 1), (1, 1)]),
    "y44": ("ycc", [(4, 4), (1, 1), (1, 1)]),  # 18 blocks/MCU: only non-interleaved scans
    "frac": ("ycc", [(3, 2), (2, 1), (1, 1)]),
    "bigc": ("ycc", [(1, 1), (2, 2), (2, 2)]),
}

FULL_SIZES = [(1, 1), (7, 5), (8, 8), (16, 16), (17, 13), (33, 31), (64, 48)]
SMALL_SIZES = [(1, 1), (17, 13), (33, 31)]


def sequential_fixtures():
    # natural images: every layout at several sizes, interleaved + split
    for lname, (cs, layout) in LAYOUTS.items():
        sizes = FULL_SIZES if lname in ("gray1", "gray2x2", "c444", "c420") else SMALL_SIZES
        for (w, h) in sizes:
            f = make_natural(w, h, layout, cs, std_q(1), seed=w * 100 + h)
            grp = "nat_%s_%dx%d" % (lname, w, h)
            scripts = ["split"] if lname == "y44" else ["inter", "split"]
            for sc in scripts:
                data, lat = encode(f, seq_scans(f, sc), {"jfif": True})
                add_record("jg_%s__seq_%s" % (grp, sc), data, STATUS_OK, f)
            prog_variants(f, grp, lname, scripts=("default",))
    # a group with many script/table/marker variants on one image (per layout)
    for lname in ("c444", "c420", "gray1", "c411"):
        cs, layout = LAYOUTS[lname]
        f = make_natural(33, 31, layout, cs, std_q(1), seed=7)
        grp = "var_%s" % lname
        variants = []
        variants.append(("inter_opt", "inter", {"jfif": True}))
        variants.append(("inter_skew", "inter", {"tabmode": "skew"}))
        variants.append(("inter_flat", "inter", {"tabmode": "flat"}))
        variants.append(("split_opt", "split", {}))
        variants.append(("ycc_opt", "ycc", {"jfif": True}))
        for ri in (1, 2, 7, 1000):
            variants.append(("ri%d" % ri, "inter", {"ri": ri}))
            variants.append(("split_ri%d" % ri, "split", {"ri": ri}))
        variants.append(("fill", "inter", {"fill": True, "jfif": True}))
        variants.append(("junk", "inter", {"junk": True, "ri": 3}))
        variants.append(("junk_rst", "inter", {"junk_rst": True, "ri": 2}))
        variants.append(("comment", "inter", {"comment": True}))
        variants.append(("sof1_t23_dqt16", "inter", {"sof": 1, "dqt16": True, "_tabs": True}))
        for vname, sc, opt in variants:
            opt = dict(opt)
            scans = seq_scans(f, sc)
            if opt.pop("_tabs", False):
                n = len(f.comps)
                dt = {ci: (2 if ci == 0 else 3) for ci in range(n)}
                scans = seq_scans(f, sc, dt, dt)
            data, lat = encode(f, scans, opt)
            add_record("jg_%s__%s" % (grp, vname), data, STATUS_OK, f)
        prog_variants(f, grp, lname, extra=(1, 2, 7, 1000))
    # random coefficients: DC categories, AC sizes, ZRL, k = 63, 16-bit codes
    for lname, sizes in (("gray1", [(16, 16), (17, 13)]), ("c444", [(16, 16), (17, 13)]),
                         ("c420", [(33, 31)]), ("gray2x2", [(17, 13)])):
        cs, layout = LAYOUTS[lname]
        for (w, h) in sizes:
            f = make_random(w, h, layout, cs, flat_q(3), seed=w * 31 + h + len(layout))
            grp = "rnd_%s_%dx%d" % (lname, w, h)
            for vname, sc, opt in (("inter_opt", "inter", {}), ("inter_skew", "inter", {"tabmode": "skew"}),
                                   ("inter_flat_ri3", "inter", {"tabmode": "flat", "ri": 3}),
                                   ("split_skew", "split", {"tabmode": "skew"})):
                data, lat = encode(f, seq_scans(f, sc), opt)
                add_record("jg_%s__%s" % (grp, vname), data, STATUS_OK, f)
            prog_variants(f, grp, lname, scripts=("default", "deep"), extra=(3,))
            data, lat = encode(f, prog_scans(f, "default"), {"sof": 2, "tabmode": "skew"})
            add_record("jg_%s__prog_default_skew" % grp, data, STATUS_OK, f)
    # colour-space marker rules
    for vname, cs, opt, ids in (
            ("jfif", "ycc", {"jfif": True}, None),
            ("adobe1", "ycc", {"adobe": 1}, None),
            ("adobe0_rgb", "rgb", {"adobe": 0}, None),
            ("adobe2_ycc", "ycc", {"adobe": 2}, None),
            ("ids_rgb", "rgb", {}, [82, 71, 66]),
            ("ids_123_ycc", "ycc", {}, None),
            ("ids_other_ycc", "ycc", {}, [10, 20, 30]),
            ("jfif_beats_adobe0", "ycc", {"jfif": True, "adobe": 0}, None)):
        layout = [(1, 1)] * 3
        f = make_natural(17, 13, layout, "rgb" if cs == "rgb" else "ycc", std_q(1), seed=3)
        # the model's colour space is what the decoder must infer from the markers
        if ids:
            for c, i in zip(f.comps, ids):
                c["id"] = i
        data, lat = encode(f, seq_scans(f, "inter"), opt)
        add_record("jg_cs_%s__marker" % vname, data, STATUS_OK, f)
    # quantization-table latching: DQT 0 is redefined after component 0's scan (D-162)
    cs, layout = LAYOUTS["c444"]
    f = make_natural(17, 13, layout, cs, std_q(1), seed=5)
    qa = f.qtables[0]
    qb = flat_q(9)
    scans = seq_scans(f, "ycc")
    scans[1]["dqt"] = {0: qb}
    data, lat = encode(f, scans, {"jfif": True})
    assert lat[0] == qa
    add_record("jg_latch__dqt_redefined_after_first_scan", data, STATUS_OK, f)


def dc_only_frame(w, h, tq=0):
    """A gray frame whose AC coefficients are all zero and whose DC values vary (fast to model)."""
    f = Frame(w, h, [{"id": 1, "h": 1, "v": 1, "tq": tq}], {tq: flat_q(1)}, "gray")
    c = f.comps[0]
    f.coefs = [[[[((bx * 3 + by * 5) % 64) - 32] + [0] * 63 for bx in range(c["bw"])]
                for by in range(c["bh"])]]
    return f


def special_fixtures():
    # EOB runs at the size limits: 16384 blocks of zero AC = one EOB14 run; 32768 blocks hit the
    # 0x7FFF flush and leave a run of 1. Expected pixels stored as a CRC-32.
    for (w, h, name) in ((1024, 1024, "eob14"), (1024, 2048, "eob_flush")):
        f = dc_only_frame(w, h)
        data, lat = encode(f, prog_scans(f, "default"), {"sof": 2})
        add_record("jg_big_%s__prog_default" % name, data, STATUS_OK, f, crc=True)
        data, lat = encode(f, seq_scans(f, "inter"), {})
        add_record("jg_big_%s__seq" % name, data, STATUS_OK, f, crc=True)
    # scan limit: exactly 128 scans decode, 129 are UNSUPPORTED
    cs, layout = LAYOUTS["c444"]
    f = make_random(16, 16, layout, cs, flat_q(3), seed=99)
    for ci in (1, 2):  # chroma: DC only, so the scan scripts below are complete
        for row in f.coefs[ci]:
            for blk in row:
                for i in range(1, 64):
                    blk[i] = 0

    def sc(comps, ss, se, ah, al):
        return {"comps": comps, "ss": ss, "se": se, "ah": ah, "al": al, "events": progressive_events,
                "dctab": {ci: (0 if ci == 0 else 1) for ci in comps},
                "actab": {ci: (0 if ci == 0 else 1) for ci in comps}}

    scans = [sc([0, 1, 2], 0, 0, 0, 1), sc([0, 1, 2], 0, 0, 1, 0)]
    for k in range(1, 64):
        scans.append(sc([0], k, k, 0, 1))
    for k in range(1, 64):
        scans.append(sc([0], k, k, 1, 0))
    assert len(scans) == 128
    data, lat = encode(f, scans, {"sof": 2})
    add_record("jg_scans__128", data, STATUS_OK, f)
    scans.append(sc([1], 1, 63, 0, 0))
    data, lat = encode(f, scans, {"sof": 2})
    add_record("jg_scans__129", data, STATUS_UNSUPPORTED, wh=(16, 16))

    # An EOB run that claims to extend past a restart: the decoder resets the run at the restart
    # (D-160), so blocks 0-1 are the zero-AC run's and block 2 onwards are coded afresh.
    f = dc_only_frame(32, 8)
    rng = Rng(4242)
    for bx in (2, 3):
        blk = f.coefs[0][0][bx]
        for _ in range(6):
            blk[ZZ[rng.range(1, 63)]] = rng.range(-9, 9)

    def run_across_restart(fr, scan, ri):
        ev = []
        at = scan["actab"][0]
        ev.append(("h", 1, at, 2 << 4))  # EOBRUN of 4 blocks, but only 2 blocks fit before the RST
        ev.append(("b", 0, 2))
        ev.append(("rst",))
        st = EobState()
        for bx in (2, 3):
            ac_first_block(fr.coefs[0][0][bx], 1, 63, 0, at, st, ev)
        flush_eobrun(st, ev, at)
        return ev

    dcs = prog_scans(f, "bands")[0]
    ac = dict(dcs, ss=1, se=63, events=run_across_restart)
    data, lat = encode(f, [dict(dcs), ac], {"sof": 2, "ri": 2})
    add_record("jg_eobrun_across_restart__prog", data, STATUS_OK, f)

    # a progressive file in which component 2 never gets any scan: INVALID at the EOI
    cs, layout = LAYOUTS["c444"]
    f = make_natural(16, 16, layout, cs, std_q(1), seed=11)
    scans = [sc for sc in prog_scans(f, "deep") if 2 not in sc["comps"]]
    data, lat = encode(f, scans, {"sof": 2})
    add_record("jg_prog_missing_component__invalid", data, STATUS_INVALID, wh=(16, 16))


def main():
    sequential_fixtures()
    special_fixtures()
    raw = b"".join(records)
    blob = struct.pack("<I", len(raw)) + zlib.compress(raw, 9)
    path = os.path.join(HERE, "jpeg-fixtures.z")
    with open(path, "wb") as fh:
        fh.write(blob)
    print("%d records, %d raw bytes, %d compressed -> %s" % (len(records), len(raw), len(blob), path))


if __name__ == "__main__":
    main()
