#!/usr/bin/env python3
"""Generates tests/data/gfx/gif-fixtures.z for libs/gfx's GIF decoder tests (M12.7, D-163/D-164).

An independent GIF writer (Python stdlib only; ARCHITECTURE section 0's host-tool exception) with
its own LZW ENCODER and its own animation COMPOSITOR. Each fixture is built from the pixel indices
the generator starts with; the expected canvases are computed from those indices and the semantics
below, never by parsing the bytes that were written. libs/gfx/gif.c must reproduce every canvas
exactly (tolerance 0).

Semantics implemented here (GIF89a plus the choices documented in gfx-image.h / D-164):
  * canvas W x H starts fully transparent (0); the logical screen's background color is ignored
  * a frame's pixels are drawn in file order (interlaced files: rows 0,8,..; 4,12,..; 2,6,..;
    1,3,..); the transparent index leaves the canvas alone; an index beyond the frame's palette
    (its local table if it has one, else the global one, else no palette) draws opaque black
  * frames are clipped to the canvas; the reported rectangle is the clipped one ({0,0,0,0} if empty)
  * before frame k is drawn, frame k-1's disposal is applied to its clipped rectangle: 2 clears it
    to transparent, 3 restores what was there before frame k-1 was drawn (frame 0 restores to
    transparent), everything else (0, 1, 4..7) leaves the canvas alone
  * a stream that ends early (too few codes, or no end-of-information code) leaves the rest of the
    frame untouched; codes past the frame's pixel count are ignored
  * the first loop extension (NETSCAPE2.0 / ANIMEXTS1.0 with sub-block byte 1 == 1) sets the loop
    count; without one the loop count is -1

The LZW encoder is written from the GIF89a appendix independently of the C decoder: after each
code it adds a table entry and widens the code when the entry just added equals 2^width, which is
one step ahead of the decoder (the final code counts as adding an entry too, so the end-of-
information code is written at the width the decoder will read it with). Once the table holds 4096
entries it stops adding and keeps emitting at width 12 (a deferred clear).

Container (zlib-compressed as a whole, prefixed by u32 LE raw length), a sequence of records:
  u16 nameLen, name, u32 W, u32 H, u32 frameCount, i32 loopCount, u32 dataLen, data,
  then per frame: u32 delayMs, u8 disposal, i32 x0, y0, x1, y1 (the clipped rectangle),
  then W*H little-endian u32 (premultiplied 0xAARRGGBB canvas after that frame is drawn).
Every fixture decodes with STATUS_OK; malformed inputs are crafted in tests/host/gfx_gif_test.c.

Run manually (`python3 tests/data/gfx/gen_gif.py`) when adding fixtures; the output is checked in,
not regenerated by the build.
"""
import os
import random
import struct
import zlib
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))

# ------------------------------------------------------------------ LZW encoder ---------------


@dataclass
class LzwOpts:
    initial_clear: bool = True
    clear_every: Optional[int] = None  # write a clear code after every N data codes
    eoi: bool = True
    tail: bytes = b""  # raw bytes appended after the end-of-information code (data past EOI)
    subblock: object = 255  # int: fixed sub-block size; "rand": random 1..255


class LzwStats:
    def __init__(self):
        self.max_width = 0
        self.codes = 0
        self.codes_after_full = 0
        self.clears = 0


def lzw_codes(indices, m, o: LzwOpts, stats: LzwStats):
    """Returns the (code, width) list for `indices`."""
    clear = 1 << m
    eoi = clear + 1
    out = []
    table = {}
    nxt = clear + 2
    w = m + 1

    def put(code):
        nonlocal w
        out.append((code, w))
        stats.max_width = max(stats.max_width, w)

    def add_step(real_key):
        """The per-code table update; real_key None for the final code (virtual entry)."""
        nonlocal nxt, w
        if nxt < 4096:
            if real_key is not None:
                table[real_key] = nxt
            e = nxt
            nxt += 1
            if e == (1 << w) and w < 12:
                w += 1
        else:
            stats.codes_after_full += 1

    def do_clear():
        nonlocal nxt, w, table
        put(clear)
        table = {}
        nxt = clear + 2
        w = m + 1
        stats.clears += 1

    if o.initial_clear:
        do_clear()
    cur = None
    since_clear = 0
    for v in indices:
        assert 0 <= v < clear
        if cur is None:
            cur = v
            continue
        key = (cur, v)
        if key in table:
            cur = table[key]
            continue
        put(cur)
        stats.codes += 1
        add_step(key)
        since_clear += 1
        cur = v
        if o.clear_every and since_clear == o.clear_every:
            do_clear()
            cur = v  # the string restarts at v: it was not yet emitted
            since_clear = 0
    if cur is not None:
        put(cur)
        stats.codes += 1
        add_step(None)
    if o.eoi:
        put(eoi)
    return out


def pack_codes(codes):
    out = bytearray()
    acc = 0
    nb = 0
    for c, w in codes:
        assert 0 <= c < (1 << w)
        acc |= c << nb
        nb += w
        while nb >= 8:
            out.append(acc & 255)
            acc >>= 8
            nb -= 8
    if nb:
        out.append(acc & 255)
    return bytes(out)


def sub_blocks(data, mode, rng):
    """Splits `data` into a terminated sub-block chain."""
    out = bytearray()
    i = 0
    while i < len(data):
        if mode == "rand":
            n = rng.randint(1, 255)
        else:
            n = int(mode)
        n = min(n, len(data) - i, 255)
        out.append(n)
        out += data[i:i + n]
        i += n
    out.append(0)
    return bytes(out)


def lzw_decode_check(codes_bytes_chain_free, m, want):
    """Self-check only (never an expectation): an ordinary LZW decoder over the packed bits must
    give back exactly `want`; catches generator bugs and pins the width rule to the standard one."""
    clear = 1 << m
    eoi = clear + 1
    bits = int.from_bytes(codes_bytes_chain_free, "little")
    nbits = len(codes_bytes_chain_free) * 8
    pos = 0
    width = m + 1
    nxt = clear + 2
    table = {}
    prev = None
    res = []

    def s(c):
        return [c] if c < clear else table[c]

    while pos + width <= nbits and len(res) < len(want):
        code = (bits >> pos) & ((1 << width) - 1)
        pos += width
        if code == clear:
            width = m + 1
            nxt = clear + 2
            table = {}
            prev = None
            continue
        if code == eoi:
            break
        if prev is None:
            assert code < clear
            res += s(code)
            prev = code
            continue
        if code < nxt:
            cs = s(code)
        else:
            assert code == nxt
            cs = s(prev) + [s(prev)[0]]
        res += cs
        if nxt < 4096:
            table[nxt] = s(prev) + [cs[0]]
            nxt += 1
            if nxt >= (1 << width) and width < 12:
                width += 1
        prev = code
    assert res[:len(want)] == want, "LZW self-check failed"


# ------------------------------------------------------------------ GIF writer ----------------

Color = Tuple[int, int, int]


@dataclass
class Frame:
    x: int
    y: int
    w: int
    h: int
    image: List[int]  # w*h indices, row-major in the LOGICAL (de-interlaced) picture
    m: int = 8
    interlace: bool = False
    lct: Optional[List[Color]] = None
    gce: Optional[Tuple[int, Optional[int], int]] = None  # (disposal, transparent index, delay)
    gce_extra: bytes = b""  # extra bytes inside the GCE sub-block (ignored by decoders)
    pre: List[bytes] = field(default_factory=list)  # raw blocks before the GCE
    lzw: LzwOpts = field(default_factory=LzwOpts)
    limit: Optional[int] = None  # code only the first `limit` file-order pixels (too few)
    extra: List[int] = field(default_factory=list)  # extra indices coded past w*h


def file_order(w, h, interlace):
    """File order of a w x h frame's pixels as (x, y); the interlace passes are the GIF89a ones."""
    if not interlace:
        rows = list(range(h))
    else:
        rows = []
        for start, step in ((0, 8), (4, 8), (2, 4), (1, 2)):
            rows += list(range(start, h, step))
    assert sorted(rows) == list(range(h))
    return [(x, y) for y in rows for x in range(w)]


def coded_stream(fr: Frame):
    pos = file_order(fr.w, fr.h, fr.interlace)
    vals = [fr.image[y * fr.w + x] for x, y in pos]
    if fr.limit is not None:
        vals = vals[:fr.limit]
    return vals + list(fr.extra)


def pal_bytes(pal):
    n = len(pal)
    assert n in (2, 4, 8, 16, 32, 64, 128, 256), n
    return b"".join(bytes(c) for c in pal)


def size_bits(n):
    return n.bit_length() - 2  # n = 2^(bits+1)


def ext(label, subs):
    out = bytes([0x21, label])
    for s in subs:
        assert 0 < len(s) < 256
        out += bytes([len(s)]) + s
    return out + b"\x00"


def netscape(loop, ident=b"NETSCAPE2.0", first=1):
    return ext(0xFF, [ident, bytes([first]) + struct.pack("<H", loop)])


def write_frame(fr: Frame, rng, stats_out):
    out = bytearray()
    for b in fr.pre:
        out += b
    if fr.gce is not None:
        disposal, transp, delay = fr.gce
        packed = (disposal << 2) | (1 if transp is not None else 0)
        body = bytes([packed]) + struct.pack("<H", delay) + bytes([transp or 0]) + fr.gce_extra
        out += ext(0xF9, [body])
    packed = (0x80 | size_bits(len(fr.lct))) if fr.lct else 0
    if fr.interlace:
        packed |= 0x40
    out += b"\x2C" + struct.pack("<HHHHB", fr.x, fr.y, fr.w, fr.h, packed)
    if fr.lct:
        out += pal_bytes(fr.lct)
    out.append(fr.m)
    stats = LzwStats()
    vals = coded_stream(fr)
    codes = lzw_codes(vals, fr.m, fr.lzw, stats)
    packed_bits = pack_codes(codes)
    # the roundtrip self-check covers streams that carry all their codes
    if fr.lzw.initial_clear or vals:
        lzw_decode_check(packed_bits, fr.m, vals)
    out += sub_blocks(packed_bits + fr.lzw.tail, fr.lzw.subblock, rng)
    stats_out.append(stats)
    return bytes(out)


@dataclass
class Gif:
    W: int
    H: int
    frames: List[Frame]
    gct: Optional[List[Color]] = None
    loop: Optional[int] = None  # NETSCAPE loop extension right after the global table
    loop_ident: bytes = b"NETSCAPE2.0"
    loop_first: int = 1
    version: bytes = b"GIF89a"
    bg_index: int = 0
    header_ext: List[bytes] = field(default_factory=list)  # extra extensions before frame 0
    expect_loop: Optional[int] = None  # override for the expected loop count


def write_gif(g: Gif, rng, stats_out):
    out = bytearray(g.version)
    packed = 0x70  # color resolution 8 bits
    if g.gct:
        packed |= 0x80 | size_bits(len(g.gct))
    out += struct.pack("<HHBBB", g.W, g.H, packed, g.bg_index, 0)
    if g.gct:
        out += pal_bytes(g.gct)
    if g.loop is not None:
        out += netscape(g.loop, g.loop_ident, g.loop_first)
    for b in g.header_ext:
        out += b
    for fr in g.frames:
        out += write_frame(fr, rng, stats_out)
    out.append(0x3B)
    return bytes(out)


# ------------------------------------------------------------------ compositor ----------------


def clip_rect(fr: Frame, W, H):
    x0, y0 = min(fr.x, W), min(fr.y, H)
    x1, y1 = min(fr.x + fr.w, W), min(fr.y + fr.h, H)
    if x1 <= x0 or y1 <= y0:
        return (0, 0, 0, 0)
    return (x0, y0, x1, y1)


def compose(g: Gif):
    """Expected (delayMs, disposal, rect, canvas) per frame, from the source indices."""
    W, H = g.W, g.H
    canvas = [0] * (W * H)
    saved = {}
    prev = None
    res = []
    for fr in g.frames:
        if prev is not None:
            pdisp, prect = prev
            x0, y0, x1, y1 = prect
            for y in range(y0, y1):
                for x in range(x0, x1):
                    if pdisp == 2:
                        canvas[y * W + x] = 0
                    elif pdisp == 3:
                        canvas[y * W + x] = saved[(x, y)]
        disp = fr.gce[0] if fr.gce else 0
        transp = fr.gce[1] if fr.gce else None
        delay = fr.gce[2] if fr.gce else 0
        rect = clip_rect(fr, W, H)
        if disp == 3:
            saved = {}
            x0, y0, x1, y1 = rect
            for y in range(y0, y1):
                for x in range(x0, x1):
                    saved[(x, y)] = canvas[y * W + x]
        pal = fr.lct if fr.lct else (g.gct if g.gct else [])
        vals = coded_stream(fr)
        pos = file_order(fr.w, fr.h, fr.interlace)
        for i in range(min(len(vals), fr.w * fr.h)):
            x, y = pos[i]
            idx = vals[i]
            cx, cy = fr.x + x, fr.y + y
            if cx >= W or cy >= H:
                continue
            if transp is not None and idx == transp:
                continue
            if idx < len(pal):
                r, gg, b = pal[idx]
                canvas[cy * W + cx] = 0xFF000000 | (r << 16) | (gg << 8) | b
            else:
                canvas[cy * W + cx] = 0xFF000000
        res.append((delay * 10, disp, rect, list(canvas)))
        prev = (disp, rect)
    return res


def loop_of(g: Gif):
    if g.expect_loop is not None:
        return g.expect_loop
    return g.loop if (g.loop is not None and g.loop_first == 1 and
                      g.loop_ident in (b"NETSCAPE2.0", b"ANIMEXTS1.0")) else -1


# ------------------------------------------------------------------ fixtures ------------------


def seeded(name):
    return random.Random(zlib.crc32(name.encode()))


def palette(n, rng):
    pal = []
    for i in range(n):
        pal.append((rng.randrange(256), rng.randrange(256), rng.randrange(256)))
    return pal


def rand_image(w, h, ncolors, rng):
    return [rng.randrange(ncolors) for _ in range(w * h)]


def full(W, H, ncolors, rng, **kw):
    return Frame(0, 0, W, H, rand_image(W, H, ncolors, rng), **kw)


def fixtures():
    out = []  # (name, Gif)

    def add(name, g):
        out.append((name, g))

    # --- LZW: every minimum code size, sub-block layouts -------------------------------------
    for m in range(2, 9):
        name = "lzw_m%d" % m
        rng = seeded(name)
        pal = palette(1 << m if m >= 2 else 2, rng)
        fr = full(17, 13, 1 << m, rng, m=m, lzw=LzwOpts(subblock="rand"))
        add(name, Gif(17, 13, [fr], gct=pal))
    for m in (9, 10, 11):
        name = "lzw_m%d_beyond_palette" % m
        rng = seeded(name)
        pal = palette(256, rng)
        fr = full(23, 19, 1 << m, rng, m=m, lzw=LzwOpts(subblock="rand"))
        add(name, Gif(23, 19, [fr], gct=pal))
    name = "lzw_m8_transparent_255"
    rng = seeded(name)
    fr = full(16, 16, 256, rng, m=8, gce=(1, 255, 4))
    add(name, Gif(16, 16, [fr], gct=palette(256, rng)))
    for sb in (1, 2, 3, 255, "rand"):
        name = "lzw_subblock_%s" % sb
        rng = seeded(name)
        fr = full(31, 29, 16, rng, m=4, lzw=LzwOpts(subblock=sb))
        add(name, Gif(31, 29, [fr], gct=palette(16, rng)))
    name = "lzw_width_3_to_12_m2"
    rng = seeded(name)
    fr = full(140, 120, 4, rng, m=2, lzw=LzwOpts(subblock="rand"))
    add(name, Gif(140, 120, [fr], gct=palette(4, rng)))
    name = "lzw_width_9_to_12_m8_clear_at_full"
    rng = seeded(name)
    fr = full(90, 70, 256, rng, m=8, lzw=LzwOpts(clear_every=3838))
    add(name, Gif(90, 70, [fr], gct=palette(256, rng)))
    name = "lzw_deferred_clear_m8"
    rng = seeded(name)
    fr = full(200, 160, 256, rng, m=8)
    add(name, Gif(200, 160, [fr], gct=palette(256, rng)))
    name = "lzw_deferred_clear_m5_smooth"
    rng = seeded(name)
    img = []
    for y in range(120):
        for x in range(150):
            img.append((x // 3 + (y // 5) * 7 + rng.randrange(3)) % 32)
    add(name, Gif(150, 120, [Frame(0, 0, 150, 120, img, m=5)], gct=palette(32, rng)))
    name = "lzw_clear_mid_stream"
    rng = seeded(name)
    fr = full(40, 30, 16, rng, m=4, lzw=LzwOpts(clear_every=37))
    add(name, Gif(40, 30, [fr], gct=palette(16, rng)))
    name = "lzw_clear_every_code"
    rng = seeded(name)
    fr = full(9, 9, 4, rng, m=2, lzw=LzwOpts(clear_every=1))
    add(name, Gif(9, 9, [fr], gct=palette(4, rng)))
    name = "lzw_no_initial_clear"
    rng = seeded(name)
    fr = full(20, 20, 8, rng, m=3, lzw=LzwOpts(initial_clear=False))
    add(name, Gif(20, 20, [fr], gct=palette(8, rng)))
    name = "lzw_no_eoi_exact_count"
    rng = seeded(name)
    fr = full(21, 17, 8, rng, m=3, lzw=LzwOpts(eoi=False))
    add(name, Gif(21, 17, [fr], gct=palette(8, rng)))
    name = "lzw_data_past_eoi"
    rng = seeded(name)
    fr = full(21, 17, 8, rng, m=3, lzw=LzwOpts(tail=bytes(rng.randrange(256) for _ in range(40))))
    add(name, Gif(21, 17, [fr], gct=palette(8, rng)))
    # Without an EOI the padding bits after the last code must be too few to form a code, or a
    # decoder reads them as an extra code: m=7 keeps the width at 8 or more (padding is < 8 bits).
    for lim in (0, 1, 37, 300):
        for eoi in (True, False):
            name = "lzw_too_few_pixels_%d%s" % (lim, "" if eoi else "_noeoi")
            rng = seeded(name)
            m = 3 if eoi else 7
            img = rand_image(20, 20, 1 << m, rng)
            base = Frame(0, 0, 20, 20, [1] * 400, m=m, gce=(1, None, 2))
            fr = Frame(0, 0, 20, 20, img, m=m, limit=lim, lzw=LzwOpts(eoi=eoi))
            add(name, Gif(20, 20, [base, fr], gct=palette(1 << m, rng)))
    name = "lzw_too_many_pixels"
    rng = seeded(name)
    fr = Frame(0, 0, 12, 9, rand_image(12, 9, 8, rng), m=3,
               extra=[rng.randrange(8) for _ in range(500)], lzw=LzwOpts(eoi=False))
    add(name, Gif(12, 9, [fr], gct=palette(8, rng)))
    name = "lzw_kwkwk_uniform"
    add(name, Gif(30, 30, [Frame(0, 0, 30, 30, [3] * 900, m=2)], gct=palette(4, seeded(name))))
    name = "lzw_kwkwk_pair"
    add(name, Gif(31, 20, [Frame(0, 0, 31, 20, [(i % 2) for i in range(620)], m=2)],
                  gct=palette(4, seeded(name))))
    name = "lzw_kwkwk_runs"
    rng = seeded(name)
    img = []
    while len(img) < 800:
        img += [rng.randrange(4)] * rng.randrange(1, 40)
    img = img[:800]
    add(name, Gif(40, 20, [Frame(0, 0, 40, 20, img, m=2)], gct=palette(4, rng)))

    # --- interlace ------------------------------------------------------------------------
    for h in range(1, 21):
        name = "interlace_h%d" % h
        rng = seeded(name)
        fr = Frame(0, 0, 5, h, rand_image(5, h, 8, rng), m=3, interlace=True)
        add(name, Gif(5, h, [fr], gct=palette(8, rng)))
    name = "interlace_offset_clipped"
    rng = seeded(name)
    fr = Frame(3, 4, 9, 23, rand_image(9, 23, 8, rng), m=3, interlace=True, gce=(0, 2, 1))
    add(name, Gif(10, 18, [Frame(0, 0, 10, 18, [5] * 180, m=3), fr], gct=palette(8, rng)))
    name = "interlace_too_few_pixels"
    rng = seeded(name)
    fr = Frame(0, 0, 6, 17, rand_image(6, 17, 8, rng), m=3, interlace=True, limit=41)
    add(name, Gif(6, 17, [Frame(0, 0, 6, 17, [1] * 102, m=3), fr], gct=palette(8, rng)))

    # --- transparency and disposal -------------------------------------------------------
    for d in range(8):
        name = "disposal_%d" % d
        rng = seeded(name)
        W, H = 24, 20
        pal = palette(8, rng)
        bg = Frame(0, 0, W, H, [1 + ((x // 4 + y // 4) % 3) for y in range(H) for x in range(W)],
                   m=3, gce=(1, None, 5))
        f1 = Frame(4, 3, 12, 10, rand_image(12, 10, 8, rng), m=3, gce=(d, 0, 7))
        f2 = Frame(10, 8, 12, 10, rand_image(12, 10, 8, rng), m=3, gce=(d, 6, 9))
        f3 = Frame(0, 0, 8, 8, rand_image(8, 8, 8, rng), m=3, gce=(0, 7, 11))
        f4 = Frame(6, 0, 18, 20, rand_image(18, 20, 8, rng), m=3, gce=(1, 0, 13))
        add(name, Gif(W, H, [bg, f1, f2, f3, f4], gct=pal, loop=0))
    name = "disposal_3_frame0"
    rng = seeded(name)
    f0 = Frame(2, 2, 10, 8, rand_image(10, 8, 8, rng), m=3, gce=(3, None, 3))
    f1 = Frame(8, 6, 8, 8, rand_image(8, 8, 8, rng), m=3, gce=(0, 0, 3))
    add(name, Gif(16, 14, [f0, f1], gct=palette(8, rng)))
    name = "disposal_3_nested"
    rng = seeded(name)
    fs = [Frame(0, 0, 16, 12, [2 + (x + y) % 5 for y in range(12) for x in range(16)], m=3,
                gce=(1, None, 1))]
    for i in range(6):
        fs.append(Frame(1 + i * 2, 1 + i, 7, 6, rand_image(7, 6, 8, rng), m=3,
                        gce=(3 if i % 3 != 2 else 2, 0, 2 + i)))
    add(name, Gif(16, 12, fs, gct=palette(8, rng)))
    name = "disposal_2_then_3_then_1"
    rng = seeded(name)
    fs = []
    for i, d in enumerate((2, 3, 1, 3, 2, 0, 3)):
        fs.append(Frame(i, i, 10, 9, rand_image(10, 9, 4, rng), m=2, gce=(d, i % 4, i)))
    add(name, Gif(20, 20, fs, gct=palette(4, rng)))
    name = "all_transparent_frame"
    rng = seeded(name)
    fs = [Frame(0, 0, 8, 8, [1] * 64, m=2, gce=(1, None, 1)),
          Frame(0, 0, 8, 8, [0] * 64, m=2, gce=(0, 0, 1)),
          Frame(2, 2, 3, 3, [0, 1, 2] * 3, m=2, gce=(2, 1, 1)),
          Frame(0, 0, 8, 8, [0] * 64, m=2, gce=(0, 0, 1))]
    add(name, Gif(8, 8, fs, gct=palette(4, rng)))
    name = "transparent_index_beyond_palette"
    rng = seeded(name)
    fs = [Frame(0, 0, 8, 8, [1] * 64, m=3, gce=(1, None, 1)),
          Frame(0, 0, 8, 8, [(i * 3) % 8 for i in range(64)], m=3, gce=(0, 5, 1))]
    add(name, Gif(8, 8, fs, gct=palette(4, rng)))
    name = "gce_disposal_without_transparency"
    rng = seeded(name)
    fs = [Frame(0, 0, 12, 12, rand_image(12, 12, 8, rng), m=3, gce=(2, None, 1)),
          Frame(4, 4, 4, 4, [1, 2, 3, 4] * 4, m=3)]
    add(name, Gif(12, 12, fs, gct=palette(8, rng)))
    name = "gce_last_wins_and_applies_once"
    rng = seeded(name)
    f0 = Frame(0, 0, 6, 6, [1] * 36, m=2, gce=(1, None, 3))
    f1 = Frame(0, 0, 6, 6, [1, 2] * 18, m=2, gce=(0, 1, 30),
               pre=[ext(0xF9, [bytes([(2 << 2) | 1, 5, 0, 2])])])  # overridden by the next GCE
    f2 = Frame(2, 2, 2, 2, [3, 3, 3, 3], m=2)  # no GCE: delay 0, disposal 0, no transparency
    add(name, Gif(6, 6, [f0, f1, f2], gct=palette(4, rng)))
    name = "gce_extra_bytes"
    rng = seeded(name)
    fr = Frame(0, 0, 6, 6, [(i % 3) for i in range(36)], m=2, gce=(1, 1, 65535),
               gce_extra=b"\x01\x02\x03")
    add(name, Gif(6, 6, [fr], gct=palette(4, rng)))
    name = "delays"
    rng = seeded(name)
    fs = [Frame(0, 0, 4, 4, [i % 4] * 16, m=2, gce=(0, None, dl)) for i, dl in
          enumerate((0, 1, 2, 7, 100, 65535))]
    add(name, Gif(4, 4, fs, gct=palette(4, rng)))

    # --- clipping and frame geometry ------------------------------------------------------
    name = "clip_partial_right_bottom"
    rng = seeded(name)
    fs = [Frame(0, 0, 10, 8, [2] * 80, m=2, gce=(1, None, 1)),
          Frame(6, 5, 9, 9, rand_image(9, 9, 4, rng), m=2, gce=(3, None, 1)),
          Frame(2, 2, 3, 3, [3] * 9, m=2, gce=(2, None, 1)),
          Frame(0, 0, 10, 8, [1] * 80, m=2, gce=(0, 1, 1))]
    add(name, Gif(10, 8, fs, gct=palette(4, rng)))
    name = "clip_fully_outside"
    rng = seeded(name)
    fs = [Frame(0, 0, 6, 6, [1] * 36, m=2, gce=(1, None, 1)),
          Frame(6, 0, 4, 4, rand_image(4, 4, 4, rng), m=2, gce=(2, None, 1)),
          Frame(0, 6, 4, 4, rand_image(4, 4, 4, rng), m=2, gce=(3, None, 1)),
          Frame(65535, 65535, 1, 1, [2], m=2, gce=(2, None, 1)),
          Frame(30000, 2, 35535, 2, [1] * (35535 * 2), m=2, gce=(2, None, 1)),
          Frame(1, 1, 2, 2, [3] * 4, m=2, gce=(0, None, 1))]
    add(name, Gif(6, 6, fs, gct=palette(4, rng)))
    name = "clip_frame_larger_than_canvas"
    rng = seeded(name)
    fs = [Frame(0, 0, 20, 20, rand_image(20, 20, 8, rng), m=3, gce=(1, None, 1)),
          Frame(0, 0, 31, 29, rand_image(31, 29, 8, rng), m=3, interlace=True, gce=(2, 3, 1)),
          Frame(0, 0, 6, 6, [4] * 36, m=3, gce=(0, None, 1))]
    add(name, Gif(9, 7, fs, gct=palette(8, rng)))
    name = "clip_last_column_row"
    rng = seeded(name)
    fs = [Frame(9, 0, 3, 10, rand_image(3, 10, 4, rng), m=2, gce=(3, None, 1)),
          Frame(0, 9, 10, 3, rand_image(10, 3, 4, rng), m=2, gce=(3, None, 1)),
          Frame(9, 9, 1, 1, [2], m=2, gce=(0, None, 1))]
    add(name, Gif(10, 10, fs, gct=palette(4, rng)))
    name = "zero_area_frames"
    rng = seeded(name)
    fs = [Frame(0, 0, 5, 5, [2] * 25, m=2, gce=(1, None, 1)),
          Frame(1, 1, 0, 3, [], m=2, gce=(2, None, 2)),
          Frame(1, 1, 3, 0, [], m=2, gce=(3, None, 2)),
          Frame(2, 2, 2, 2, [1] * 4, m=2, gce=(0, None, 2))]
    add(name, Gif(5, 5, fs, gct=palette(4, rng)))
    name = "one_by_one"
    add(name, Gif(1, 1, [Frame(0, 0, 1, 1, [1], m=2)], gct=palette(2, seeded(name))))
    name = "wide_and_tall"
    rng = seeded(name)
    add(name, Gif(300, 1, [full(300, 1, 4, rng, m=2)], gct=palette(4, rng)))
    add("tall", Gif(1, 300, [full(1, 300, 4, rng, m=2, interlace=True)], gct=palette(4, rng)))

    # --- palettes -------------------------------------------------------------------------
    name = "lct_smaller_than_index_range"
    rng = seeded(name)
    fr = full(16, 16, 16, rng, m=4, lct=palette(4, rng))
    add(name, Gif(16, 16, [fr], gct=palette(16, rng)))
    name = "lct_overrides_gct_per_frame"
    rng = seeded(name)
    fs = [full(8, 8, 4, rng, m=2, lct=palette(4, rng), gce=(1, None, 1)),
          Frame(2, 2, 4, 4, rand_image(4, 4, 4, rng), m=2, gce=(0, None, 1)),
          Frame(3, 3, 4, 4, rand_image(4, 4, 4, rng), m=2, lct=palette(2, rng), gce=(0, 0, 1))]
    add(name, Gif(8, 8, fs, gct=palette(4, rng)))
    name = "lct_only_no_gct"
    rng = seeded(name)
    fr = full(11, 9, 8, rng, m=3, lct=palette(8, rng))
    add(name, Gif(11, 9, [fr], gct=None))
    name = "no_palette_all_black"
    rng = seeded(name)
    fs = [full(9, 9, 4, rng, m=2, gce=(1, None, 1)),
          Frame(2, 2, 5, 5, rand_image(5, 5, 4, rng), m=2, gce=(0, 1, 1))]
    add(name, Gif(9, 9, fs, gct=None))
    name = "background_index_ignored"
    rng = seeded(name)
    fr = Frame(3, 3, 4, 4, rand_image(4, 4, 4, rng), m=2)
    add(name, Gif(10, 10, [fr], gct=palette(4, rng), bg_index=2))
    name = "gct_256_lct_256"
    rng = seeded(name)
    fs = [full(16, 16, 256, rng, m=8, lct=palette(256, rng))]
    add(name, Gif(16, 16, fs, gct=palette(256, rng)))

    # --- extensions, loop counts, versions ---------------------------------------------
    name = "ext_comment_plaintext_unknown"
    rng = seeded(name)
    pt = ext(0x01, [struct.pack("<HHHHBBBB", 0, 0, 8, 8, 4, 8, 1, 0), b"hello", b" world"])
    cm = ext(0xFE, [b"a comment", b"in two blocks"])
    unk = ext(0x99, [b"\x00\x01\x02", b"xyz"])
    app = ext(0xFF, [b"XMP DataXMP", b"<x:xmp/>"])
    empty_comment = b"\x21\xFE\x00"
    fs = [Frame(0, 0, 8, 8, rand_image(8, 8, 4, rng), m=2, pre=[cm, pt], gce=(1, None, 4)),
          Frame(1, 1, 6, 6, rand_image(6, 6, 4, rng), m=2, pre=[unk, app, empty_comment],
                gce=(0, 0, 4))]
    add(name, Gif(8, 8, fs, gct=palette(4, rng), header_ext=[cm, unk]))
    for lp in (0, 5, 65535):
        name = "loop_%d" % lp
        rng = seeded(name)
        fs = [Frame(0, 0, 4, 4, [i % 4] * 16, m=2, gce=(0, None, 3)) for i in range(3)]
        add(name, Gif(4, 4, fs, gct=palette(4, rng), loop=lp))
    name = "loop_animexts"
    rng = seeded(name)
    add(name, Gif(4, 4, [Frame(0, 0, 4, 4, [1] * 16, m=2, gce=(0, None, 3)),
                         Frame(0, 0, 4, 4, [2] * 16, m=2, gce=(0, None, 3))],
                  gct=palette(4, rng), loop=3, loop_ident=b"ANIMEXTS1.0"))
    name = "loop_not_first_byte_1"
    rng = seeded(name)
    add(name, Gif(4, 4, [Frame(0, 0, 4, 4, [1] * 16, m=2)], gct=palette(4, rng), loop=9,
                  loop_first=2))
    name = "loop_other_application"
    rng = seeded(name)
    add(name, Gif(4, 4, [Frame(0, 0, 4, 4, [1] * 16, m=2)], gct=palette(4, rng), loop=9,
                  loop_ident=b"NETSCAPE2.1"))
    name = "loop_short_data_block"
    rng = seeded(name)
    add(name, Gif(4, 4, [Frame(0, 0, 4, 4, [1] * 16, m=2)], gct=palette(4, rng),
                  header_ext=[ext(0xFF, [b"NETSCAPE2.0", b"\x01\x07"])]))
    name = "loop_between_frames_first_wins"
    rng = seeded(name)
    fs = [Frame(0, 0, 4, 4, [1] * 16, m=2, gce=(0, None, 1)),
          Frame(0, 0, 4, 4, [2] * 16, m=2, gce=(0, None, 1),
                pre=[netscape(4), netscape(8)]),
          Frame(0, 0, 4, 4, [3] * 16, m=2, gce=(0, None, 1))]
    add(name, Gif(4, 4, fs, gct=palette(4, rng), expect_loop=4))
    name = "gif87a_single"
    rng = seeded(name)
    add(name, Gif(13, 7, [full(13, 7, 8, rng, m=3)], gct=palette(8, rng), version=b"GIF87a"))
    name = "gif87a_two_frames"
    rng = seeded(name)
    add(name, Gif(13, 7, [full(13, 7, 8, rng, m=3), Frame(3, 2, 5, 3, [7] * 15, m=3)],
                  gct=palette(8, rng), version=b"GIF87a"))
    name = "many_frames"
    rng = seeded(name)
    fs = []
    for i in range(70):
        fs.append(Frame(i % 5, (i * 3) % 7, 4, 3, [(i + j) % 4 for j in range(12)], m=2,
                        gce=(i % 4, None, i)))
    add(name, Gif(10, 12, fs, gct=palette(4, rng)))
    name = "large_photo_like"
    rng = seeded(name)
    img = []
    for y in range(120):
        for x in range(160):
            img.append(((x * 3) // 2 + y + rng.randrange(4)) % 64)
    add(name, Gif(160, 120, [Frame(0, 0, 160, 120, img, m=6, interlace=True)],
                  gct=palette(64, rng)))
    return out


def main():
    blob = bytearray()
    fx = fixtures()
    names = set()
    agg = LzwStats()
    for name, g in fx:
        assert name not in names, name
        names.add(name)
        rng = seeded(name + "/layout")
        stats = []
        data = write_gif(g, rng, stats)
        for s in stats:
            agg.max_width = max(agg.max_width, s.max_width)
            agg.codes_after_full += s.codes_after_full
        frames = compose(g)
        nb = name.encode()
        blob += struct.pack("<H", len(nb)) + nb
        blob += struct.pack("<IIIiI", g.W, g.H, len(frames), loop_of(g), len(data)) + data
        for delay_ms, disp, rect, canvas in frames:
            assert len(canvas) == g.W * g.H
            blob += struct.pack("<IB4i", delay_ms, disp, *rect)
            blob += b"".join(struct.pack("<I", v) for v in canvas)
    # generator assertions: the corner cases the decoder tests rely on are really present
    assert agg.max_width == 12, "no stream reached 12-bit codes"
    assert agg.codes_after_full > 100, "no stream continued past a full table"
    with open(os.path.join(HERE, "gif-fixtures.z"), "wb") as f:
        f.write(struct.pack("<I", len(blob)) + zlib.compress(bytes(blob), 9))
    print(len(fx), "fixtures,", len(blob), "bytes raw")


if __name__ == "__main__":
    main()
