# Generates build/include/branding.h from branding/{name,version,codenames.tsv}, the only
# place the OS name and version live (ARCHITECTURE §0, D-046).
BRANDING_HDR := $(BUILD)/include/branding.h

.PHONY: branding
branding: $(BRANDING_HDR)

$(BRANDING_HDR): branding/name branding/version branding/codenames.tsv
	@mkdir -p $(dir $@)
	@name=$$(cat branding/name); \
	version=$$(cat branding/version); \
	phase=$$(echo "$$version" | cut -d. -f2); \
	codename=$$(awk -F'\t' -v p="$$phase" '$$1==p {print $$2}' branding/codenames.tsv); \
	[ -n "$$codename" ] || codename="unreleased"; \
	{ \
	  echo "/* Generated by mk/branding.mk from branding/. Do not edit by hand. */"; \
	  echo "#ifndef BONGOS_BRANDING_H"; \
	  echo "#define BONGOS_BRANDING_H"; \
	  echo; \
	  echo "#define BONGOS_NAME \"$$name\""; \
	  echo "#define BONGOS_VERSION \"$$version\""; \
	  echo "#define BONGOS_CODENAME \"$$codename\""; \
	  echo; \
	  echo "#endif"; \
	} > $@
