/* The console font's PSF2 shape (ARCHITECTURE §5.2/§19, D-069) and the linked-in font data
 * itself, shared between the loader and the kernel the same way bootinfo.h is: both link
 * build/gen/console-font.c (generated by `tools/mkfont c` from the checked-in
 * data/fonts/console.psf, see mk/font.mk), so the font is available even if reading it from the
 * ESP would fail, and no BootInfo field or ABI change is needed to hand it off. */
#ifndef BOOT_COMMON_CONSOLE_FONT_H
#define BOOT_COMMON_CONSOLE_FONT_H

#include <stdint.h>

#define PSF2_MAGIC          0x864AB572u
#define PSF2_HEADERSIZE     32u
#define CONSOLE_FONT_WIDTH  8u
#define CONSOLE_FONT_HEIGHT 16u
#define CONSOLE_FONT_LENGTH 128u /* glyph count; only 0x00 and 0x20-0x7E are ever drawn from */

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint32_t headersize; /* offset of glyph 0's first byte */
    uint32_t flags;      /* 0: no Unicode table */
    uint32_t length;     /* glyph count */
    uint32_t charsize;   /* bytes per glyph: one byte per row for an 8-wide font */
    uint32_t height;
    uint32_t width;
} Psf2Header;

/* Generated by tools/mkfont (build/gen/console-font.c) from data/fonts/console.psf: the raw
 * PSF2 file bytes (a Psf2Header followed by CONSOLE_FONT_LENGTH * CONSOLE_FONT_HEIGHT glyph row
 * bytes), and its exact length. A consumer validates the header (magic/version/headersize/
 * flags/length/charsize/height/width, matching the constants above) before trusting the glyph
 * data -- see fbcon's contract (kernel/drivers/fbcon/fbcon.c). */
extern const uint8_t fontConsolePsf[];
extern const uint32_t fontConsolePsfSize;

#endif
