/* See gfx-path.h: stroking by outline pieces (D-143). Every segment, join and cap becomes a
 * closed convex polygon wound the same way (positive shoelace area, the same winding as
 * gfxPathAddRect/Ellipse); the caller fills them together with one nonzero pass, so shared edges
 * cancel exactly and there are no conflation seams. Float geometry, no libm (D-142). */
#pragma STDC FP_CONTRACT OFF

#include "gfx/gfx-internal.h"

#include <string.h>

#define ARC_TOLERANCE 0.1f
#define ARC_MAX_STEPS 200

static float clampCoord(float v) {
    return v > GFX_COORD_MAX ? GFX_COORD_MAX : (v < -GFX_COORD_MAX ? -GFX_COORD_MAX : v);
}

/* Square root by Newton iteration from a bit-pattern seed. Not `sqrtf`: under -fmath-errno that
 * can become a libm call, which libc stage 1 doesn't have. Exact enough for geometry. */
static float sqrtNewton(float x) {
    if (!(x > 0.0f)) {
        return 0.0f;
    }
    uint32_t bits;
    memcpy(&bits, &x, sizeof(bits));
    bits = 0x1FBD1DF5u + (bits >> 1);
    float y;
    memcpy(&y, &bits, sizeof(y));
    for (int i = 0; i < 4; i++) {
        y = 0.5f * (y + x / y);
    }
    return y;
}

/* One flattened subpath. */
typedef struct {
    float *x, *y;
    uint32_t n, cap;
    const GfxAllocator *alloc;
    Status error;
} Poly;

static void polyFree(Poly *p) {
    if (p->x != NULL) {
        p->alloc->free(p->alloc->ctx, p->x, p->cap * sizeof(float));
        p->alloc->free(p->alloc->ctx, p->y, p->cap * sizeof(float));
    }
    p->x = p->y = NULL;
    p->n = p->cap = 0;
}

static void polyAdd(Poly *p, float x, float y) {
    if (p->error != STATUS_OK) {
        return;
    }
    x = clampCoord(x);
    y = clampCoord(y);
    if (p->n > 0) {
        float dx = x - p->x[p->n - 1], dy = y - p->y[p->n - 1];
        if (dx * dx + dy * dy < 1e-12f) {
            return; /* a repeated point has no direction */
        }
    }
    if (p->n == p->cap) {
        uint32_t cap = p->cap != 0 ? p->cap * 2 : 32;
        if (cap > GFX_PATH_MAX_VERBS) {
            p->error = STATUS_ERR_NO_MEMORY;
            return;
        }
        float *nx = p->alloc->alloc(p->alloc->ctx, cap * sizeof(float));
        float *ny = p->alloc->alloc(p->alloc->ctx, cap * sizeof(float));
        if (nx == NULL || ny == NULL) {
            if (nx != NULL) {
                p->alloc->free(p->alloc->ctx, nx, cap * sizeof(float));
            }
            if (ny != NULL) {
                p->alloc->free(p->alloc->ctx, ny, cap * sizeof(float));
            }
            p->error = STATUS_ERR_NO_MEMORY;
            return;
        }
        if (p->x != NULL) {
            memcpy(nx, p->x, p->n * sizeof(float));
            memcpy(ny, p->y, p->n * sizeof(float));
            p->alloc->free(p->alloc->ctx, p->x, p->cap * sizeof(float));
            p->alloc->free(p->alloc->ctx, p->y, p->cap * sizeof(float));
        }
        p->x = nx;
        p->y = ny;
        p->cap = cap;
    }
    p->x[p->n] = x;
    p->y[p->n] = y;
    p->n++;
}

static void polyPoint(void *ctx, float x, float y) {
    polyAdd(ctx, x, y);
}

/* Appends the polygon as a closed subpath, reversed if needed so its winding is positive. A
 * zero-area polygon is dropped. */
static void emit(GfxPath *out, const float *xy, int n) {
    float area2 = 0.0f;
    for (int i = 0; i < n; i++) {
        int j = (i + 1) % n;
        area2 += xy[2 * i] * xy[2 * j + 1] - xy[2 * j] * xy[2 * i + 1];
    }
    if (!(area2 > 0.0f || area2 < 0.0f)) {
        return;
    }
    for (int k = 0; k < n; k++) {
        int i = area2 > 0.0f ? k : n - 1 - k;
        if (k == 0) {
            gfxPathMoveTo(out, xy[2 * i], xy[2 * i + 1]);
        } else {
            gfxPathLineTo(out, xy[2 * i], xy[2 * i + 1]);
        }
    }
    gfxPathClose(out);
}

/* A fan (P, P+v0, ..., P+v1) covering the arc of radius h from v0 to v1, rotating by dir (+1 or
 * -1, in the sense of a positive angle); `half` marks a rotation of exactly pi (v1 = -v0). Points
 * are generated by repeated rotation with polynomial sin/cos of a small step. */
static void arcFan(GfxPath *out, float px, float py, float v0x, float v0y, float v1x, float v1y,
                   float dir, float h) {
    float step = sqrtNewton(8.0f * ARC_TOLERANCE / (h > 1e-3f ? h : 1e-3f));
    step = step > 0.9f ? 0.9f : (step < 0.03f ? 0.03f : step);
    float s2 = step * step;
    float cs = 1.0f - s2 * 0.5f + s2 * s2 * (1.0f / 24.0f) - s2 * s2 * s2 * (1.0f / 720.0f);
    float sn = step * (1.0f - s2 * (1.0f / 6.0f) + s2 * s2 * (1.0f / 120.0f));
    float pts[2 * (ARC_MAX_STEPS + 4)];
    int n = 0;
    pts[n++] = px;
    pts[n++] = py;
    float vx = v0x, vy = v0y;
    pts[n++] = px + vx;
    pts[n++] = py + vy;
    for (int i = 0; i < ARC_MAX_STEPS; i++) {
        if (vx * v1x + vy * v1y >= cs * h * h) {
            break; /* the remaining angle is under one step */
        }
        float nx = vx * cs - dir * vy * sn, ny = dir * vx * sn + vy * cs;
        vx = nx;
        vy = ny;
        pts[n++] = px + vx;
        pts[n++] = py + vy;
    }
    pts[n++] = px + v1x;
    pts[n++] = py + v1y;
    emit(out, pts, n / 2);
}

static void joinAt(GfxPath *out, float px, float py, float d0x, float d0y, float d1x, float d1y,
                   float h, const GfxStroke *st) {
    float cross = d0x * d1y - d0y * d1x;
    float c = d0x * d1x + d0y * d1y;
    if (c > 0.0f && cross < 1e-6f && cross > -1e-6f) {
        return; /* collinear: the segment quads already meet flush */
    }
    float s = cross > 0.0f ? -1.0f : 1.0f; /* the outer side of the turn */
    float n0x = -d0y * h * s, n0y = d0x * h * s;
    float n1x = -d1y * h * s, n1y = d1x * h * s;
    if (st->join == GFX_JOIN_ROUND) {
        arcFan(out, px, py, n0x, n0y, n1x, n1y, cross >= 0.0f ? 1.0f : -1.0f, h);
        return;
    }
    if (st->join == GFX_JOIN_MITER) {
        float lim = st->miterLimit;
        /* miter ratio = 1/cos(phi/2) with cos^2(phi/2) = (1+c)/2, so no sqrt is needed */
        if (lim > 1.0f && (1.0f + c) * 0.5f * lim * lim >= 1.0f) {
            float k = 1.0f / (1.0f + c);
            float pts[8] = {
                px,       py,      px + n0x, py + n0y, px + (n0x + n1x) * k, py + (n0y + n1y) * k,
                px + n1x, py + n1y};
            emit(out, pts, 4);
            return;
        }
    }
    float pts[6] = {px, py, px + n0x, py + n0y, px + n1x, py + n1y};
    emit(out, pts, 3);
}

static void capAt(GfxPath *out, float px, float py, float dx, float dy, float h, GfxCap cap) {
    float nx = -dy * h, ny = dx * h;
    if (cap == GFX_CAP_SQUARE) {
        float pts[8] = {px + nx,          py + ny,          px + nx + dx * h, py + ny + dy * h,
                        px - nx + dx * h, py - ny + dy * h, px - nx,          py - ny};
        emit(out, pts, 4);
    } else if (cap == GFX_CAP_ROUND) {
        arcFan(out, px, py, nx, ny, -nx, -ny, -1.0f, h);
    }
}

/* Strokes one flattened subpath. */
static void strokePoly(GfxPath *out, const Poly *poly, bool closed, float h, const GfxStroke *st) {
    uint32_t n = poly->n;
    const float *x = poly->x, *y = poly->y;
    if (closed && n > 1) {
        float dx = x[0] - x[n - 1], dy = y[0] - y[n - 1];
        if (dx * dx + dy * dy < 1e-12f) {
            n--; /* the closing point repeats the start */
        }
    }
    if (n == 0) {
        return;
    }
    if (n == 1) { /* no length: a dot */
        if (st->cap == GFX_CAP_ROUND) {
            gfxPathAddEllipse(out, x[0], y[0], h, h);
        } else if (st->cap == GFX_CAP_SQUARE) {
            gfxPathAddRect(out, x[0] - h, y[0] - h, 2.0f * h, 2.0f * h);
        }
        return;
    }
    uint32_t m = closed ? n : n - 1; /* segment count */
    float pdx = 0, pdy = 0, fdx = 0, fdy = 0;
    for (uint32_t i = 0; i < m; i++) {
        uint32_t j = (i + 1) % n;
        float dx = x[j] - x[i], dy = y[j] - y[i];
        float inv = 1.0f / sqrtNewton(dx * dx + dy * dy);
        dx *= inv;
        dy *= inv;
        float qx = -dy * h, qy = dx * h;
        float quad[8] = {x[i] + qx, y[i] + qy, x[j] + qx, y[j] + qy,
                         x[j] - qx, y[j] - qy, x[i] - qx, y[i] - qy};
        emit(out, quad, 4);
        if (i == 0) {
            fdx = dx;
            fdy = dy;
        } else {
            joinAt(out, x[i], y[i], pdx, pdy, dx, dy, h, st);
        }
        pdx = dx;
        pdy = dy;
    }
    if (closed) {
        joinAt(out, x[0], y[0], pdx, pdy, fdx, fdy, h, st);
    } else {
        capAt(out, x[0], y[0], -fdx, -fdy, h, st->cap);
        capAt(out, x[n - 1], y[n - 1], pdx, pdy, h, st->cap);
    }
}

Status gfxStrokeToPath(const GfxPath *in, const GfxStroke *st, GfxPath *out) {
    gfxPathReset(out);
    if (in->error != STATUS_OK) {
        return in->error;
    }
    if (!__builtin_isfinite(st->width) ||
        (st->join == GFX_JOIN_MITER && !__builtin_isfinite(st->miterLimit))) {
        return STATUS_ERR_INVALID;
    }
    if (st->width <= 0.0f) {
        return STATUS_OK;
    }
    float h = st->width * 0.5f;
    if (h > GFX_COORD_MAX) {
        h = GFX_COORD_MAX;
    }
    Poly poly = {NULL, NULL, 0, 0, out->alloc, STATUS_OK};
    bool have = false, closed = false;
    float cx = 0.0f, cy = 0.0f;
    const float *pt = in->pts;
    for (uint32_t i = 0; i < in->nVerbs && poly.error == STATUS_OK; i++) {
        switch (in->verbs[i]) {
            case GFX_VERB_MOVE:
                if (have) {
                    strokePoly(out, &poly, closed, h, st);
                }
                poly.n = 0;
                closed = false;
                have = true;
                polyAdd(&poly, pt[0], pt[1]);
                cx = pt[0];
                cy = pt[1];
                pt += 2;
                break;
            case GFX_VERB_LINE:
                polyAdd(&poly, pt[0], pt[1]);
                cx = pt[0];
                cy = pt[1];
                pt += 2;
                break;
            case GFX_VERB_QUAD: {
                float qx = pt[0], qy = pt[1], ex = pt[2], ey = pt[3];
                gfxSubdivideCubic(cx, cy, cx + (2.0f / 3.0f) * (qx - cx),
                                  cy + (2.0f / 3.0f) * (qy - cy), ex + (2.0f / 3.0f) * (qx - ex),
                                  ey + (2.0f / 3.0f) * (qy - ey), ex, ey, polyPoint, &poly);
                cx = ex;
                cy = ey;
                pt += 4;
                break;
            }
            case GFX_VERB_CUBIC:
                gfxSubdivideCubic(cx, cy, pt[0], pt[1], pt[2], pt[3], pt[4], pt[5], polyPoint,
                                  &poly);
                cx = pt[4];
                cy = pt[5];
                pt += 6;
                break;
            case GFX_VERB_CLOSE:
                closed = true;
                break;
            default:
                polyFree(&poly);
                return STATUS_ERR_INVALID;
        }
    }
    if (have && poly.error == STATUS_OK) {
        strokePoly(out, &poly, closed, h, st);
    }
    Status err = poly.error;
    polyFree(&poly);
    return err != STATUS_OK ? err : out->error;
}

Status gfxStrokePath(GfxCanvas *c, const GfxPath *p, const GfxStroke *s, GfxColor col) {
    GfxPath outline;
    gfxPathInit(&outline, c->alloc);
    Status st = gfxStrokeToPath(p, s, &outline);
    if (st == STATUS_OK) {
        st = gfxFillPath(c, &outline, GFX_FILL_NONZERO, col, GFX_OP_SRC_OVER);
    }
    gfxPathFree(&outline);
    return st;
}

Status gfxStrokeLine(GfxCanvas *c, float x0, float y0, float x1, float y1, float width,
                     GfxColor col) {
    GfxPath line;
    gfxPathInit(&line, c->alloc);
    gfxPathMoveTo(&line, x0, y0);
    gfxPathLineTo(&line, x1, y1);
    GfxStroke s = {width, GFX_CAP_BUTT, GFX_JOIN_BEVEL, 4.0f};
    Status st = gfxStrokePath(c, &line, &s, col);
    gfxPathFree(&line);
    return st;
}
