#!/usr/bin/env python3
"""Generates tests/data/png/*.png fixtures for tools/imgdiff's host tests (ARCHITECTURE §23/
D-070), using Python's stdlib `zlib` -- a host tool, ARCHITECTURE §0's host-tool exception, and
independent of bongOS's own from-scratch PNG/DEFLATE codec (tools/imgdiff/{png,zlib_wrap,inflate,
deflate}.c). Decoding these fixtures with our own decoder is therefore a real cross-check against
an independent implementation, not just a round trip through code that wrote them.

Run manually (`python3 tests/data/png/gen.py`) when adding or changing fixtures; the output PNGs
are checked in, not regenerated by the build.
"""
import os
import struct
import zlib


def paeth_predictor(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def write_png(path, width, height, rows_rgb, filter_types):
    """rows_rgb: list of `height` bytes-like objects, each width*3 long (unfiltered RGB).
    filter_types: a single int (every row) or a list of `height` ints, each 0-4."""
    if isinstance(filter_types, int):
        filter_types = [filter_types] * height
    bpp = 3
    raw = bytearray()
    prev = bytes(width * bpp)
    for y in range(height):
        cur = rows_rgb[y]
        ft = filter_types[y]
        raw.append(ft)
        for x in range(width * bpp):
            a = cur[x - bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x - bpp] if x >= bpp else 0
            v = cur[x]
            if ft == 0:
                out = v
            elif ft == 1:
                out = (v - a) & 0xFF
            elif ft == 2:
                out = (v - b) & 0xFF
            elif ft == 3:
                out = (v - ((a + b) // 2)) & 0xFF
            elif ft == 4:
                out = (v - paeth_predictor(a, b, c)) & 0xFF
            else:
                raise ValueError("bad filter type")
            raw.append(out)
        prev = cur

    def chunk(tag, data):
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    sig = bytes([137, 80, 78, 71, 13, 10, 26, 10])
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    idat = zlib.compress(bytes(raw), 9)
    with open(path, "wb") as f:
        f.write(sig)
        f.write(chunk(b"IHDR", ihdr))
        f.write(chunk(b"IDAT", idat))
        f.write(chunk(b"IEND", b""))


def solid_rows(width, height, color):
    row = bytes(color) * width
    return [row] * height


def gradient_rows(width, height):
    rows = []
    for y in range(height):
        row = bytearray()
        for x in range(width):
            row += bytes([(x * 255) // max(1, width - 1), (y * 255) // max(1, height - 1), 128])
        rows.append(bytes(row))
    return rows


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    write_png(os.path.join(here, "filter0_solid.png"), 8, 8, solid_rows(8, 8, (200, 100, 50)), 0)
    write_png(os.path.join(here, "filter1_sub.png"), 8, 8, gradient_rows(8, 8), 1)
    write_png(os.path.join(here, "filter2_up.png"), 8, 8, gradient_rows(8, 8), 2)
    write_png(os.path.join(here, "filter3_avg.png"), 8, 8, gradient_rows(8, 8), 3)
    write_png(os.path.join(here, "filter4_paeth.png"), 8, 8, gradient_rows(8, 8), 4)
    write_png(os.path.join(here, "mixed_filters.png"), 16, 16, gradient_rows(16, 16), [0, 1, 2, 3, 4] * 4)
    print("wrote fixtures to", here)


if __name__ == "__main__":
    main()
