/* tools/ksyms: builds the kernel's embedded symbol table, KSYM v1 (docs/specs/ksyms.md, D-075).
 * A host tool (own clang, no cross flags), per ARCHITECTURE §0's host-tool exception.
 *
 * Two-pass link (mk/kernel.mk):
 *   ksyms empty                  > build/gen/ksyms-empty.c   (pass 1: an empty placeholder blob)
 *   ksyms gen kernel.pass1.elf   > build/gen/ksyms.c         (pass 2: the real blob)
 *   ksyms check kernel.elf                                   (post-pass-2: verify byte-for-byte)
 */
#include "elf-read.h"
#include "ksyms-encode.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static _Noreturn void die(const char *msg) {
    fprintf(stderr, "ksyms: %s\n", msg);
    exit(1);
}

static void emitC(FILE *out, const char *sourceNote, const KsymsBlob *blob) {
    fprintf(out, "/* Generated by tools/ksyms from %s. Do not edit by hand. */\n", sourceNote);
    fprintf(out, "#include <stdint.h>\n\n");
    fprintf(out, "__attribute__((section(\".ksyms\"), used, aligned(8))) const uint8_t "
                 "ksymsData[] = {\n");
    for (size_t i = 0; i < blob->size; i++) {
        fprintf(out, "%s0x%02x,%s", (i % 12 == 0) ? "    " : "", blob->data[i],
                (i % 12 == 11 || i + 1 == blob->size) ? "\n" : " ");
    }
    if (blob->size == 0) {
        fprintf(out, "\n");
    }
    fprintf(out, "};\n");
    fprintf(out, "const uint32_t ksymsDataSize = %zu;\n", blob->size);
}

static void cmdEmpty(void) {
    KsymsBlob blob = ksymsEncodeEmpty();
    emitC(stdout, "(no input -- pass-1 placeholder)", &blob);
    ksymsBlobFree(&blob);
}

static void cmdGen(const char *elfPath) {
    uint64_t textBase, textEnd;
    if (!elfReadSymbolValue(elfPath, "kernelTextStart", &textBase) ||
        !elfReadSymbolValue(elfPath, "kernelTextEnd", &textEnd)) {
        die("kernelTextStart/kernelTextEnd not found in the given ELF");
    }
    ElfFuncSymList syms = elfReadFuncSyms(elfPath);
    KsymsBlob blob = ksymsEncode(&syms, textBase, textEnd);
    emitC(stdout, elfPath, &blob);
    ksymsBlobFree(&blob);
    elfFuncSymListFree(&syms);
}

static void cmdCheck(const char *elfPath) {
    uint64_t textBase, textEnd;
    if (!elfReadSymbolValue(elfPath, "kernelTextStart", &textBase) ||
        !elfReadSymbolValue(elfPath, "kernelTextEnd", &textEnd)) {
        die("kernelTextStart/kernelTextEnd not found in the given ELF");
    }
    ElfFuncSymList syms = elfReadFuncSyms(elfPath);
    KsymsBlob expected = ksymsEncode(&syms, textBase, textEnd);

    uint8_t *actual = NULL;
    size_t actualSize = 0;
    if (!elfReadSection(elfPath, ".ksyms", &actual, &actualSize)) {
        die("the given ELF has no .ksyms section");
    }

    if (actualSize != expected.size || memcmp(actual, expected.data, expected.size) != 0) {
        fprintf(stderr,
                "ksyms: check FAILED: %s's .ksyms section (%zu bytes) doesn't match a fresh "
                "encoding of its own symbols (%zu bytes) -- something in the kernel's text "
                "depends on the .ksyms blob's own size, or .ksyms isn't placed after every "
                "instruction that could reference a symbol address\n",
                elfPath, actualSize, expected.size);
        exit(1);
    }

    free(actual);
    ksymsBlobFree(&expected);
    elfFuncSymListFree(&syms);
}

static void usage(const char *argv0) {
    fprintf(stderr,
            "usage: %s empty\n"
            "       %s gen ELF.elf\n"
            "       %s check ELF.elf\n",
            argv0, argv0, argv0);
    exit(2);
}

int main(int argc, char **argv) {
    if (argc == 2 && strcmp(argv[1], "empty") == 0) {
        cmdEmpty();
    } else if (argc == 3 && strcmp(argv[1], "gen") == 0) {
        cmdGen(argv[2]);
    } else if (argc == 3 && strcmp(argv[1], "check") == 0) {
        cmdCheck(argv[2]);
    } else {
        usage(argv[0]);
    }
    return 0;
}
