#!/bin/bash
# Generates build/include/branding.h from branding/{name,version,codenames.tsv}. The OS name,
# version, and codename live only in branding/ (D-046); this is the one place that turns them
# into C, so a rename touches one directory. Mirrors the phase math in
# .github/workflows/release.yml (phase <= 15 -> "0.<phase>.<n>", else "1.<phase-15>.<n>").
set -euo pipefail

clean() { tr -d '\r\n'; }
escape() { sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

name=$(clean < branding/name | escape)
version=$(clean < branding/version)
versionEscaped=$(printf '%s' "$version" | escape)

major=$(echo "$version" | cut -d. -f1)
minor=$(echo "$version" | cut -d. -f2)
if [ "$major" -ge 1 ]; then
    phase=$((minor + 15))
else
    phase=$minor
fi
codename=$(awk -F'\t' -v p="$phase" '$1 == p { print $2 }' branding/codenames.tsv)
[ -n "$codename" ] || codename="unreleased"
codename=$(printf '%s' "$codename" | escape)

cat <<HEADER
/* Generated by tools/gen-branding.sh from branding/. Do not edit by hand. */
#ifndef BRANDING_H
#define BRANDING_H

#define BRANDING_NAME "$name"
#define BRANDING_VERSION "$versionEscaped"
#define BRANDING_CODENAME "$codename"

#endif
HEADER
